### ISSUE TITLE
Remove Stained Glass

### ISSUE THREAD

**Issue by labpaw** [skyboy/MineFactoryReloaded#196]
It's not needed anymore. Stained Glass added in 1.7

**Comment by SuperBrainAK** [comment]
what is the reason why this hasnt been resolved? I am unable to craft laser foci without insane difficulty. if removing the glass panes cannot be done then can there be a secondary recipe for the laser foci so it can use the vanilla glass panes?

**Comment by AnrDaemon** [comment]
You're either using bogus mod version, or bogus scripts that alter crafting recipes.
MFR glass panes can only crafted from MFR glass, and do not interfere with vanilla panes.

**Comment by SuperBrainAK** [comment]
I am currently using 2.8.1-174, which was downloaded from powercrystals' main site. I have scoured the internet for an hour and only came up with this page that lists the 2.8.2 version but does not have a download link available https://openeye.openmods.info/mod/minefactoryreloaded instructions on where to get a non "bogus" version or to check for these "scripts that alter recipies" would be appreciated. I am only mildly frustrated but I truly have never heard of other mods altering other mods' recipes only their own which is dependent on other mods being present.

**Comment by AnrDaemon** [comment]
/facepalm http://minecraft.curseforge.com/projects/minefactory-reloaded
So much for "scouring the internet", if you miss the one stop shop…

**Comment by SuperBrainAK** [comment]
that is 2.8.1-174 which is what I have

**Comment by AnrDaemon** [comment]
Then go back to your oculist.

**Comment by bookerthegeek** [comment]
I would love to see a screenshot of that recipe, and a mod list.

**Comment by SuperBrainAK** [comment]
tried using the DL from the linked Curse page and the exact same thing happens, mod list and screens provided: https://postimg.org/gallery/2zduk0any/
I am crafting MFR stained Glass Blocks from vanilla Glass using Ceramic Dye but it turns back into vanilla Stained Glass Panes which are useless.

**Comment by AnrDaemon** [comment]
![javaw-20160702-093747 03](https://cloud.githubusercontent.com/assets/6532485/16538849/0572ed3e-4039-11e6-9627-0084eb88f576.png)

**Comment by skyboy** [comment]
a mod is rewriting MFR's `MFR glass -> MFR glass panes` recipe to `MFR glass -> vanilla glass panes` because it thinks what i have done is incorrect (it's not - if you mix MFR's stained glass with another stained glass you get vanilla panes).

There are two workarounds for when mods do this, since I did anticipate it - first, craft MFR's stained glass panes directly from vanilla glass panes.
 If for some reason this is also failing, you can apply MFR's ceramic dye to a vanilla glass pane in-world to get an MFR stained glass pane, which you may then silk touch.

**Comment by SuperBrainAK** [comment]
I dont know why I didnt try dying the panes initially, but that works flawlessly. anyway I have painfully tested one mod at a time and found that it is only when I have all of these mods ( https://postimg.org/image/unwraho71/ ) enabled does it get modified, removing any one of them will cause it to change to the MFR panes. am I running into some recipe database limit here?

**Comment by bookerthegeek** [comment]
What is in the 1.7.10 folder?

**Comment by SuperBrainAK** [comment]
CodeChickenLib-1.7.10-1.1.3.138-universal
ForgeMultipart-1.7.10-1.2.0.345-universal
MrTJPCore-1.1.0.33-universal

**Comment by AnrDaemon** [comment]
Try this one. Unlikely it'll help, but still…
https://github.com/Chicken-Bones/EnderStorage/issues/65#issuecomment-163246471

**Comment by SuperBrainAK** [comment]
nope, didnt fix it

**Comment by bookerthegeek** [comment]
@SuperBrainAK are you using MultiMC? If so,  can you export you instance and send it to me? Either dropbox it and send me the link or just email it. It's my username, and it's at Gmail.
