### ISSUE TITLE
Issue with Conveyor Belts on going up

### ISSUE THREAD

**Issue by zlepper** [skyboy/MineFactoryReloaded#333]
The conveyor belts doesn't seem to want to transport items uphill. 

The attached pictures show a setup that doesn't want to transport the Item Collector. 

This only seems to happen in multiplayer, at least I can't reproduce it in singleplayer. 
The server it was tested on is running Cauldron, which might be the cause of the issue.

![2014-12-21_18 54 28](https://cloud.githubusercontent.com/assets/1499810/5519070/d59229bc-8942-11e4-964d-ca91c64b5e8b.png)
![2014-12-21_18 54 30](https://cloud.githubusercontent.com/assets/1499810/5519072/d596614e-8942-11e4-8512-502f18453a39.png)
![2014-12-21_18 54 31](https://cloud.githubusercontent.com/assets/1499810/5519071/d594f232-8942-11e4-820c-8bf23860c72c.png)

**Comment by BDweller** [comment]
The problem seems to be serverside.

On  the servers I saw this happen the items would move clientside up the slopes and " revert" back tot heir s stuck position once the server updates.

**Comment by bochen415** [comment]
https://bugs.mojang.com/browse/MC-4
