### ISSUE TITLE
Chunkloader has huge energi storage

### ISSUE THREAD

**Issue by zlepper** [skyboy/MineFactoryReloaded#338]
Is it intended for the chunkloader to have int.MAXVALUE as it storage capacity?
It seems a bit excesive. 

mfr version: 2.8.0RC6-5.

**Comment by skyboy** [comment]
Yes, this is intended. If configured to ignore the chunk limit, then the chunk loader will load as many chunks as you can supply it energy for (~1.3 billion RF/t at 39 chunk radius).
