### ISSUE TITLE
Support custom material names

### ISSUE THREAD

**Issue by Adaptivity** [skyboy/MineFactoryReloaded#340]
Since MineFactoryReloaded adds 2 new materials to TiC there are some issues with translating them.
Basically I need different adjective ends for some tools(toolparts). Some examples:
1. Plastic Pickaxe -> Пластиковая(adj end="ая") кирка(tool) (in Russian)
2. Plastic Hatchet -> Пластиковый(adj end="ый" different from above) топорик(tool) (in Russian)
Tinkers Construct already supports custom material names:
1. How it looks in .lang file: https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tinker/lang/en_US.lang#L917
2. And possibly in code: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/tools/items/ToolPart.java (not sure about this, hope you can find out it yourself)

**Comment by skyboy** [comment]
You should be able to just do like what you did here: https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tinker/lang/ru_RU.lang#L1410
in MFR's localization file, but it seems that currently mod materials aren't supported properly for localization like the tcon materials are

**Comment by Adaptivity** [comment]
They actually working. Tested.
