### ISSUE TITLE
Issue compiling org.mozilla.javascript.EcmaError: ReferenceError: "com" is not defined.

### ISSUE THREAD

**Issue by clienthax** [skyboy/MineFactoryReloaded#349]
git cloned and run ant

http://pastebin.ubuntu.com/9690400/

**Comment by skyboy** [comment]
What version of the JDK are you using? This works on both 1.6_45 (Rhino engine) and 1.8 (Nashorn)

**Comment by clienthax** [comment]
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

**Comment by XxCoolGamesxX** [comment]
Sure, Update to 1.8.0_25 of Java.

**Comment by clienthax** [comment]
@skyboy seems to of fixed it on windows, thanks ;)
