### ISSUE TITLE
EnetBridge compat

### ISSUE THREAD

**Issue by gigabit101** [skyboy/MineFactoryReloaded#353]
When powering a MFR machine with EnetBridge installed there is a check to see if the machine can take RF or EU.
In result mfr machines can accept both so it just keeps checking.
Is it possible to add a config to turn off Ic2/Eu support for the machine?

**Comment by skyboy** [comment]
MFR machines cannot accept both. Further, I do not accept bugs with ENetBridge installed as a result of it corrupting MFR machines in some circumstances.
