### ISSUE TITLE
Chunk loader does not remember settings on server restart

### ISSUE THREAD

**Issue by tgstyle** [skyboy/MineFactoryReloaded#357]
Using version 2.8.0RC6-32.jar

After a server restart the radius is always at 0.

**Comment by tgstyle** [comment]
I am using latest 2.8.0RC6-47 and this is still happening. It does not keep the amount of power stored or the radius. Also when you adjust the radius on server restart it will allow you to go past 2.

**Comment by skyboy** [comment]
Going to need the log.

**Comment by tgstyle** [comment]
Hope this one helps.

http://paste.ubuntu.com/10115054/

**Comment by skyboy** [comment]
There's nothing in your log indicating anything happened.

**Comment by tgstyle** [comment]
Hmm odd, in my case it is not hard to replicate. Place a chunk loader on a server, give it power, set the radius. Shut down the server, and start it back up. Log in to the server and look at the chunk loader, it has 0 radius and no power stored. Not sure if it matters but the server is running on Fedora 21.

**Comment by tgstyle** [comment]
I may have something, I saw something pop up in the console that was never put in the log.

http://paste.ubuntu.com/10145567/
