### ISSUE TITLE
Thaumcraft Manabean support is outdated

### ISSUE THREAD

**Issue by Barhandar** [skyboy/MineFactoryReloaded#358]
Thaumcraft 4.2 has changed mechanics of manabeans: they're now placed against bottom of the block, not the side like cocoa, and the manabean's aspect determines the pod's aspect.

Planters place unaspected Mana Pods regardless of input manabean, resulting in random primals growing, and only place them if there's log available to the side, like with cocoa. They will attempt to place (and fail, and drop the random-primal bean) even if no log is available at the top.

Neither Fruit Pickers nor Harvesters harvest mana pods.

**Comment by ulkoko** [comment]
I Got a little impatient and fixed the issue.
(at least it works for me now)

edited src/powercrystals/minefactoryreloaded/modhelpers/thaumcraft/Thaumcraft.java
and added src/powercrystals/minefactoryreloaded/modhelpers/thaumcraft/PlantableMana.java

update files at
https://github.com/ulkoko/MineFactoryReloaded

I have no idea whether that's the proper way to contribute, and I apologize if it isn't.
I never did anything like this before.
