### ISSUE TITLE
improvement for dsu (Item window)

### ISSUE THREAD

**Issue by HadesDurin** [skyboy/MineFactoryReloaded#360]
so i searched and found nothing
so here is what i think of:
can there be a label or a item window for the dsu to see what it holds

my problem i am facing is, that every time i enter the room where my dsu's are placed
it needs some time to find the right dsu
and when you are not using ae2 or something else to find items then it takes a while...

**Comment by skyboy** [comment]
There are [Items Frames](http://minecraft.gamepedia.com/Item_Frame) you can use.
