### ISSUE TITLE
Road blocks only function in positive derictions

### ISSUE THREAD

**Issue by magnus97** [skyboy/MineFactoryReloaded#363]
The road blocks when walked on in negative direction you go normal speed but in positive direction you walk faster.

**Comment by Barhandar** [comment]
Noticed that as well. When I'm going East, it speeds me up, West, doesn't. Going diagonally (forward+strafe) results in bursts of extreme speed throwing me off the road. Ended up replacing the road with Carpenter's Blocks so there's no speed effect.
