### ISSUE TITLE
Harvester/Planter not working with BOP plants

### ISSUE THREAD

**Issue by Sunnyice** [skyboy/MineFactoryReloaded#364]
Harvester does not harvest BOP woods.
Planter does not plant BOP saplings.

BiomesOPlenty-1.7.10-2.1.0.1057
CoFHCore-[1.7.10]3.0.0B9-40
MineFactoryReloaded-[1.7.10]2.8.0RC6-5
ThermalExpansion-[1.7.10]4.0.0B8-23
ThermalFoundation-[1.7.10]1.0.0RC1-13

**Comment by skyboy** [comment]
Support for BoP has been on BoP's side for some time now.
