### ISSUE TITLE
Grinder and Slaughterhouse crash server

### ISSUE THREAD

**Issue by CourtArtanis** [skyboy/MineFactoryReloaded#365]
Hi,
MFR version 2.8.0RC6-5.jar
Please see: https://gist.github.com/CourtArtanis/a09fe71f19159c96ca30

When cow is spawned, slaughterhouse attempts to kill, but this error happens each time.
To fix this I have to load the world in MCedit and remove the machines/entities, otherwise the world will not restart.
So far it's been reproduced in multiple environments, with different spawn area sizes and positioning of spawners/machinery.

This is a Cauldron server, however, running version MCPC-Plus-1.7.10-1.1236.06.212, which I understand to be the last available version. I am aware MFR and Cauldron don't like each other, also that this error may not be your problem, but I'm really hoping I can find some kind of workaround from an MFR point of view, other than "remove cauldron/MFR/don't use the machines".

Thanks :)

**Comment by skyboy** [comment]
This is an issue with cauldron.
