### ISSUE TITLE
RC5 -> RC6 broke enderio energy conduit on harvesters

### ISSUE THREAD

**Issue by japherwocky** [skyboy/MineFactoryReloaded#366]
Not sure this is on your end, but anyhow - with RC5, enderio energy conduits worked with everything, in RC6 they are working with planters, but not with harvesters!

I can do a more thorough check of machines if you'd like.  Or you can close this out; not sure if you are trying to be compatible with enderio.

**Comment by bochen415** [comment]
1. Post the modlist (with versions)
2. Post the Forge version.
3. Did you break the block in question and placed it again?
4. Did you update MFR lately without updating EnderIO (suspecting RF API update quirk)

**Comment by japherwocky** [comment]
ahh ty ty, you are right -- I had missed the EnderIO update
