### ISSUE TITLE
Buildcraft pipes don't connect to some machines

### ISSUE THREAD

**Issue by Jerdo** [skyboy/MineFactoryReloaded#374]
Some of the machines don't connect to buildcraft kinesis pipes. This happens for example with the slaugtherhouse, laser drill and chronotyper. On other machines it's working (harvester, grinder, breeder). Also fluid pipes from buildcraft doesn't seem to connect to the slaughterhouse graphically, but fluid is output anyways.

Of course, this could be a buildcraft issue. But since some machines are working and some don't, I thought this would more likely be a MFR issue.

Mod versions I tested this with:
Buildcraft versions: 6.3.4/6.3.6
MFR versions: 1.7.10 2.8.0RC6-45, 2.8.0RC6-47, 2.8.0RC6-5

**Comment by skyboy** [comment]
Is this still an issue?

**Comment by LouisHutch** [comment]
https://github.com/BuildCraft/BuildCraft/issues/2861

**Comment by skyboy** [comment]
Apparently not.
