### ISSUE TITLE
Client crash - placing mfr harvester

### ISSUE THREAD

**Issue by tjsd** [skyboy/MineFactoryReloaded#377]
Version: MineFactoryReloaded-[1.7.10]2.8.0RC6-57
Other mod I suspect: EnderIO-1.7.10-2.2.8.350
Crash Report: http://pastebin.com/zH6z46CH

I placed down a mfr harvester, and the broke it with a dark steel pickaxe from ender io, with silk touch enchantment on.

It no longer stacks with other harvester, and when I place it down I instantly crash. When I get back in the harvester is placed but the "bad one" is still in my inventory.

**Comment by skyboy** [comment]
Duplicates https://github.com/skyboy/MineFactoryReloaded/issues/376
