### ISSUE TITLE
crash happens during startup

### ISSUE THREAD

**Issue by Sailren** [skyboy/MineFactoryReloaded#381]
http://paste.ubuntu.com/10372734/

used version: MineFactoryReloaded{1.7.10R2.8.0RC7} and EnderIO{1.7.10-2.2.8.352}

the top offender is ender io, i posted it here anyway cuz it also mentions mfr

**Comment by skyboy** [comment]
You need to update to Forge 1291 to fix this.

**Comment by Sailren** [comment]
so no gregtech for now xD, he wants 1263 because of some texture errors :D
