### ISSUE TITLE
i get this error when i load world related to grinder ?

### ISSUE THREAD

**Issue by abdullamu** [skyboy/MineFactoryReloaded#382]
http://paste.ubuntu.com/10373530/

when i use MineFactoryReloaded-[1.7.10]2.8.0RC7-72   or above i get this error trying to load my world and crash

**Comment by randomness911** [comment]
I get the same error. Happens in single players and multiplayer as soon as a grinder is placed or looked at.


http://pastebin.com/zYKzWVgu

**Comment by jermangarc** [comment]
Same here. using RC7-75

**Comment by skyboy** [comment]
Use the release version of MFR, not the alpha.
