### ISSUE TITLE
Grinder spam chat

### ISSUE THREAD

**Issue by quienti** [skyboy/MineFactoryReloaded#385]
I have this message all time on my chat  => death.attack.mfr.grinder

And on server =>  [Server thread/INFO] : death.attack.mfr.grinder

MFR version : 2.8.0RC7.75

**Comment by PavelInt** [comment]
Try release MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar or last build.

**Comment by jermangarc** [comment]
COFH Core was updated and created new config files. Look for the config file in your config directory: config/cofh/core/common.cfg.

Make sure the setting is set to false in the "general" section up top.
# Set to true to display death messages for any named entity.
    B:EnableGenericDeathMessage=false

This is not a Minefactory reloaded issue.

**Comment by Ephys** [comment]
The fact that it outputs "death.attack.mfr.grinder" instead of a localized message is

**Comment by Lunatrius** [comment]
Most likely [this](https://github.com/skyboy/MineFactoryReloaded/blob/44cba2c3052d2b99f675b47191c586dbd1fccf85/src/powercrystals/minefactoryreloaded/core/GrindingDamage.java#L48-L49).

**Comment by skyboy** [comment]
Resolved by https://github.com/skyboy/MineFactoryReloaded/commit/44b5e71697d627d305818e58e8f510c89cc88fab
