### ISSUE TITLE
MineFactory Reloaded for FTB Infinity 1.2.0 glitches out screen (1.2.1 too)

### ISSUE THREAD

**Issue by DarkReaper115** [skyboy/MineFactoryReloaded#389]
So my friend tried to use the 1.2.0 verion of FTB Infinity modpack and when it loaded up her menu screen was shrinked into a corner and it looked like this: http://i.imgur.com/XIS5naz.png

After removing all the mods and readding them one by one, she realised that it was MineFactory Reloaded the one causing the issue. The pack will load with no problems is she removes just MFR.

I will attach her console logs and a dxdiag file for reference.

EDIT: She has tried adding -Dforge.forceNoStencil=true to the launcher parameters too, as many websites advice. It didnt work.

EDIT 2: Same Issue on Infinity 1.2.1, mostly cause MFR didnt update there :(

![ftb log](https://cloud.githubusercontent.com/assets/11265621/6436261/5d50ebf2-c08b-11e4-90f3-6bf08784a2a3.png)
![dxdiag](https://cloud.githubusercontent.com/assets/11265621/6436262/5d5fddf6-c08b-11e4-9919-bc7ed856f5de.png)
![dxdiag2](https://cloud.githubusercontent.com/assets/11265621/6436263/5d6564c4-c08b-11e4-93db-5e0cec40b1a7.png)

**Comment by PavelInt** [comment]
Use win x64 and 4Gb Memory.

**Comment by skyboy** [comment]
Fixed in newer releases.
