### ISSUE TITLE
Mob Grinder Ignoring NBT Data on Thaumcraft Wisp Essence

### ISSUE THREAD

**Issue by ErdrickXLII** [skyboy/MineFactoryReloaded#395]
When a Mob Grinder kills a Thaumcraft Wisp, and puts the dropped item into a chest, if the first acceptable slot it finds already has an Essence in it, it will just increase the stack size in that slot, ignoring the fact that the two items have different NBT data on them, and are thus technically different items and shouldn't stack with each other.

**Comment by skyboy** [comment]
Fixed in dev
