### ISSUE TITLE
EU support is broken.

### ISSUE THREAD

**Issue by Wuerfel21** [skyboy/MineFactoryReloaded#396]
Well, what the title states:
IC2 cable: doesnt connect to MFR machine
Rednet cable: connects to MFSU, but doesnt seem to transfer any energy(Edit: seems to transfer, but power bar in GUI is bugged)

Both latest versions

**Comment by skyboy** [comment]
IC2 cables aren't supposed to connect, they've never worked correctly.

Which gui is bugged? The MFSU's? That wouldn't be my bug.

**Comment by Wuerfel21** [comment]
No, the mfr machine i tried it with, the red power bar just wasnt there, whereas hovering above it showed the power in it (for some random reason in RF).

**Comment by skyboy** [comment]
The powerbar is an issue with your texture pack, you will need to wait for it to update.
