### ISSUE TITLE
Thaumcraft Compatibility Broken

### ISSUE THREAD

**Issue by WittyYeti** [skyboy/MineFactoryReloaded#399]
**Java**: 1.8
**Minecraft Version**: 1.7.10
**Minecraft Forge Version**: 10.13.2.1291
**Crash Report**: http://paste.ee/p/dBt7x
**MFR Version**: 2.8.0RC8-88
**Thaumcraft Version**: 1.7.10-4.2.3.5

The crash happens upon world creation. I have tried all world types. I've also tried loading with just MFR and Thaumcraft loaded, the same thing happens.

**Comment by skyboy** [comment]
This is an issue with thaumcraft and one of it's addons (I cannot remember which one it is); It's adding aspects to nuggets, and thaumcraft's crucible recipe handler for aspects gets stuck in an infinite loop (nuggets result in more nuggets via the crucible) when MFR adds some aspects to its items.

**Comment by jermangarc** [comment]
I believe it might be Witching Gadgets
