### ISSUE TITLE
Crash when trying to put items into planter filter.

### ISSUE THREAD

**Issue by LightningLdr180** [skyboy/MineFactoryReloaded#400]
Version 2.8.0RC8-86 - When I try to place anything (ie. potatoes, carrots) into the filter side of the MFR Planter I get disconnected from the server with "A fatal error has occured, this connection is terminated."

Here is the log of the server when this happens:
http://pastebin.com/CTrAewL6

I have tried with different items, and is definately reproducible every time.

**Comment by skyboy** [comment]
Mod list?

**Comment by LightningLdr180** [comment]
After further investigation the issue is only when connected to the server through BungeeCord.  If I direct connect this crash does not occur.  If BungeeCord is not supported, which I assume is the case, I apologize and you can close this and I can take it up with them.

**Comment by skyboy** [comment]
In this particular instance it appears that the player's entity ID doesn't match between server and client, which is something BungeeCord will need to correct on their end.
