### ISSUE TITLE
Mekanism mod capability

### ISSUE THREAD

**Issue by JFMillerUSA** [skyboy/MineFactoryReloaded#403]
Trying to use Auto Anvil with Mekanisms Obsidian Armor and Obsidian Ingots. Also some Logistical Transporters won't connect to some machines (Grinder, Harvester, Composter, Sludge Boiler)

**Comment by ktole1999** [comment]
put a chest between machine and pipe

**Comment by skyboy** [comment]
Logistical Transporters are out of my reach, but the Auto-Anvil definitely now works with properly registered mod armor & ingots.
