### ISSUE TITLE
BioReactor and Dyes

### ISSUE THREAD

**Issue by Thiana** [skyboy/MineFactoryReloaded#404]
I'm not sure if this is intended behavior or simply an oversight, BioReactors appear to no longer accept (vanilla) dyes to generate BioFuel. I've checked google and have not been able to find anything about this being an intended behavior change. Thanks

![2015-03-20_20 47 02](https://cloud.githubusercontent.com/assets/405832/6762998/4337f7f4-cf42-11e4-80a2-835720a9c2c8.png)

**Comment by skyboy** [comment]
Accepting dyes was a bug, and it will not be reintroduced.
