### ISSUE TITLE
[Suggestion] Better Glass Pane Rendering

### ISSUE THREAD

**Issue by Radviger** [skyboy/MineFactoryReloaded#411]
Some screenshots:
http://prntscr.com/6mtlqm
http://prntscr.com/6mtm9t
Thanks!

**Comment by skyboy** [comment]
The first screenshot is an issue in vanilla minecraft introduced for 1.7 and fixed for 1.8; This is the only version that displays the problem.

Second screenshot is an issue in my rendering code, but it hasn't been a high priority to fix.
