### ISSUE TITLE
Troubles with Thaumcraft

### ISSUE THREAD

**Issue by Glowstonesword** [skyboy/MineFactoryReloaded#412]
On world creation, kicks to main menu and only partially generates world file - meaning the game is unplayable. Seems to be a problem with MinefactoryReloaded|CompatThaumcraft.

http://pastebin.com/d3v30hgP

**Comment by Glowstonesword** [comment]
Further testing reveals the issue to be Witching Gadgets, an addon for Thaumcraft: http://www.curse.com/mc-mods/minecraft/228268-witching-gadgets

Not sure what's wrong with it, but without it the game runs fine.

**Comment by skyboy** [comment]
Witching Gadgets is causing Thaumcraft to enter an infinite loop when MFR adds aspects to its items.

**Comment by BluSunrize** [comment]
Disable nugget transmutation in the config
