### ISSUE TITLE
[Suggestion] Configurable road velocity boost.

### ISSUE THREAD

**Issue by TheCadde** [skyboy/MineFactoryReloaded#416]
May i make a request for a config option to set road block boost multiplier?
More specifically, a config for this...

[BlockFactoryRoad.java#L39](https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/block/transport/BlockFactoryRoad.java#L39)
`final double boost = 1.5 * slipperiness;`

Where the constant "1.5" is a config variable.

Pretty please?

**Comment by TheCadde** [comment]
To add my own side of the story, my joy comes from playing in an as realistic manner as possible.
The idea of roads is nice, i even wish walking on grass made one slower. Especially in certain biomes like swamps etc, but that is beside the point.

The problem here is that the current boost makes roads more powerful than steam locomotives from RailCraft. Heck, even horses become an unnecessary thing to have once you've laid some roads.
I would like roads to give a minimal boost to my walking speed, somewhere close to how fast i move while sprinting... without needing to sprint. And then of course if i am sprinting, moving "that much faster" on a road.

On a side note, not sure if necessary or even easy... Haven't even tried...
But using a horse on a road should have a separate boost applied if possible. Like i said, haven't tried but i fear using a horse on a road would make me move stupidly fast? I would be perfectly fine if horses, unlike the player, didn't get much of a boost at all. If any, configurable would be the best, IMHO.

**Comment by skyboy** [comment]
I can not make this configurable due to the way players move, however it can be reduced.
