### ISSUE TITLE
[Suggestion/Request] DSU - Lock mode

### ISSUE THREAD

**Issue by Protheus** [skyboy/MineFactoryReloaded#427]
Feature request for the DSU to lock the DSU so there is always one item in the DSU. Like the locking of a Jabba or Cache from TE

**Comment by blockbreaker1361** [comment]
This is an awesome suggestion. I really hope they accept this and implement it. :)

**Comment by SJ1133** [comment]
+1 to this. A Simple idea but brilliant

**Comment by Protheus** [comment]
guess this will not happen :-(

**Comment by skyboy** [comment]
It's been a planned feature for a [considerable amount of time](https://github.com/skyboy/MineFactoryReloaded/blob/master/resources/assets/minefactoryreloaded/textures/blocks/machines/tile.mfr.machine.deepstorageunit.active.side.png)

It's just not a priority.
