### ISSUE TITLE
Grinder and wither skelleton = no necrotic bone

### ISSUE THREAD

**Issue by jaz000** [skyboy/MineFactoryReloaded#429]
Necrotic bone is a drop from the wither skelleton added by Tinker's Construct.
When the grinder grinds a wither skelleton is only drops regular bones
Just wondered if it was possible for the grinder to do the Tinker's special drops (there may be others for other mobs)

MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar
CoFHCore-[1.7.10]3.0.1-254.jar
ThermalFoundation-[1.7.10]1.0.0-81.jar

**Comment by skyboy** [comment]
This is something that must be addressed on Tinker's Construct side.
