### ISSUE TITLE
Liquid Router Issue

### ISSUE THREAD

**Issue by HandGrenade** [skyboy/MineFactoryReloaded#431]
I am currently on the FTB Infinity modpack (Version 1.3.4), and whenever I try to place an empty, or full bucket inside the Liquid Router, It kicks me to title screen. When I log back in the bucket has not been placed in the Liquid Router. 

Thankyou :)

**Comment by skyboy** [comment]
I need the logs detailing what error occurred. They may be in either the server or client files.

**Comment by HandGrenade** [comment]
I have now tested on Singleplayer, and the bug does not happen there. I have also tested multiple times now and It now, instead of kicking me to title screen, kicks me to the server's lobby. (I'm guessing the kick to title screen was not related to MFR) The following log was all that occurred from when I placed the bucket in the Liquid Router, until I was loaded and in the lobby. http://pastebin.com/jn4VnAfV

**Comment by skyboy** [comment]
Closing this since there has been no reply.
