### ISSUE TITLE
[Suggestion] Speed upgrades

### ISSUE THREAD

**Issue by nigraforce** [skyboy/MineFactoryReloaded#432]
Some machines, like harvesters, have a pretty decent speed of working. Some other machines, like auto-enchanters that do 30 levels of echanting, are rather slow. 
How about speed upgrades? With speed upgrades, you can:
1) Make machines scale from early game to endgame. 
2) Balance machines in TE manner. Planter + harvester + fertilizer combo is very powerful because harvester works very fast and you can fill two 64-stacks JABBA barrels with logs and charcoal in 2 to 3 hours. However, if you implement speed upgrades, you can limit the player in the early game and give more possibilites to players in the endgame, like make a fully-upgraded harvester chop off an entire tree treecapitator-style or just harvest 3x3x3 chunks of wood at a time.
3) Suffice players' thirst for powercreep. We can build big reactors that pump out thousands of RF per tick, we can build a frame-quarry that can mine out an entire chunk in a minute, but we also have an auto-enchanter that needs more than a minute to enchant an item and an auto-spawner that is not comparable to EnderIO's auto-spawner because of how slow it is. 
How awesome would be to use a x64 overclocked mining laser instead of a frame-quarry, or to build a mob-grinding facility that can generate a diamond chest of loot in ten minutes?

Well, actually, all 3 of my points are about balancing the machines, but whatever.

**Comment by Ianaver** [comment]
agreed

**Comment by skyboy** [comment]
Implemented by https://github.com/skyboy/MineFactoryReloaded/commit/3ae0dda29eff2155f71329c9c774b34c92e4f051 (though the items are only provided by TE/other mods at present)
