### ISSUE TITLE
Server crashing : /

### ISSUE THREAD

**Issue by evernife** [skyboy/MineFactoryReloaded#442]
http://pastebin.com/aQ2CAEkE
http://pastebin.com/20fWf4Av

(Using latestest version)

**Comment by skyboy** [comment]
Fixed by https://github.com/skyboy/MineFactoryReloaded/commit/e4cc41e6a9a89950f4b2ee7ba5126c3674fc6bcc

**Comment by evernife** [comment]
whrre can i download the fixed version? (jenkins site?)
