### ISSUE TITLE
no limit to harvester pathfinding distance

### ISSUE THREAD

**Issue by jtait** [skyboy/MineFactoryReloaded#443]
Harvester cut down trees by connecting through a forest, over 200 blocks away from the harvester.  This caused frame rate issues, not to mention destroying the forest.  Need to place a limit on the range of the harvester.

**Comment by jtait** [comment]
using MineFactoryReloaded-[1.7.10]2.8.0-104

**Comment by skyboy** [comment]
The limit is in the config.

**Comment by jtait** [comment]
sorry, didn't realize.  Maybe a good idea to change the default to a smaller value though.
