### ISSUE TITLE
Memory leak on world change from unknown source.

### ISSUE THREAD

**Issue by NolanSyKinsley** [skyboy/MineFactoryReloaded#445]
I was on IRC yesterday and showed a heap dump to Skyboy showing a memory leak on dimension change. I don't know whether it is caused by MFR, iChunUtils, or Ars Magica 2. It builds up over repeated ports to the main world, eventually running the client out of memory. He suggested I go through a nether portal or use /cofh tpx and it would clear the usage by MFR. That did not work so I have gathered another memory dump that is taken after making the leak symptomatic, then going to the nether and back out, then taking the snapshot. This is what it shows: http://i.imgur.com/h7MyAIW.png Here is the compressed dump: https://www.dropbox.com/s/jvogyhftgx84agz/latest.hprof.tar.gz

**Comment by skyboy** [comment]
Fixed by ff8b1fa21a908c99e3d45079667dd34ddb7ecef3
