### ISSUE TITLE
Caught exception from MineFactoryReloaded|CompatThaumcraft, without Witching Gadgets

### ISSUE THREAD

**Issue by Zarkazm** [skyboy/MineFactoryReloaded#446]
Java: 1.8.0.45 x64
Minecraft Version: 1.7.10
Minecraft Forge Version: 10.13.3.1388 & 10.13.3.1408
Crash Report: https://pste.me/#/mfr-thaum
MFR Version: 2.8.0-104
Thaumcraft Version: 4.2.3.5

Azanor/thaumcraft#1698
powercrystals/MineFactoryReloaded/issues/415
BluSunrize/WitchingGadgets/issues/14
skyboy/MineFactoryReloaded/issues/399
skyboy/MineFactoryReloaded/issues/419

So i've been reading a lot about this, hence the above referenced issues, and everything i've read points to the addon Witching Gadgets being the issue.  Problem is though, I don't have this addon.  In fact, I had never heard of it until I was researching this error.

More to this story, i'm only just now getting this problem when going through and updating my mods to the latest versions, deleting some old ones i'm not using, and adding a few new ones.  I've gone through the Thaumcraft addons i've updated, reverting them back to the known working versions, but still receive the error.

Another kick to this error is that it doesn't always happen.  While reverting my Thaumcraft addons back and forth, i'd get the error, close my client, revert back a mod version, load up, create a new world, and it would work.  Close out for the night, come back the next day, and error again.

Also, it's not just on New World; it's happening on existing worlds that loaded fine before, even with the same mods and versions.

**Comment by Zarkazm** [comment]
Update: So i've been individually reverting the non-thaumcraft addon mods that I had updated and I think I found the problem.  It appears to have been the new Magical Crops Beta build (magicalcrops-4.0.0_PUBLIC_BETA_3).  I reverted back to "magicalcrops-1.7.10_0.1" that i've been using, and I haven't seen the MFR-Thaumcraft Compat error in several client restarts, new worlds, or existing world loads.

**Comment by abdullamu** [comment]
i have the same thing so we should inform magical crops devs if this is related to them..

**Comment by Zarkazm** [comment]
I was thinking about doing that, but figured i'd wait for skyboy to confirm it's not a MFR issue, since Azanor had mentioned previously it was an MFR issue.

**Comment by Zarkazm** [comment]
That's interesting, abdullamu.  I was looking at your issue tickets with Project E, and Project E was actually one of the mods I had updated when my problem started.  I updated from 1.4.5 to 1.4.7, but reverting back to 1.4.5 did not fix my issue.  It makes me wonder if the problem isn't caused by a particular mod at all and the problem is in the way MFR is doing something.  In reading the other issues regarding Witching Gadgets, i'm puzzled why MFR would assign aspects to items outside of it's mod.  Maybe we need a config option to turn this feature off until the issue is fixed later?

**Comment by abdullamu** [comment]
hum why u didnt try projectE 1.4.6 my problem happened when i update to 1.4.7 the option for u is if u havent done anything with projectE in ur world u can turn it off since MFR is essential as mod or turn off Magical crops since its Beta thing and still things are updating if u havent used it until someone find out and fix this problem and for time sake i'll inform magical crops so they can check it .

**Comment by Zarkazm** [comment]
i missed the 1.4.6 update, so in my testing i was just reverting back to my last "known working version" which was 1.4.5 at the time.  As of right now, 1.4.7 is working for me, and reverting my Magical Crops back to before the beta builds has solved my problem.

Because our problems are identical, but are appearing due to two different mods, your's being Project E and mine being Magical Crops, it leads me to think it's an MFR issue.  In fact, I wonder if you loaded the beta Magical Crops build I wouldn't be surprised if it worked for you.  Would be an interesting test.  Keep your Project E on 1.4.6 and try the Magical Crops BETA 3 build and see if you get the error.

**Comment by abdullamu** [comment]
i do use magical crops BETA 3 its part of my custom pack and its working fine as long as ProjectE is 1.4.6

**Comment by Zarkazm** [comment]
Ya, that makes me think it's an MFR issue.

**Comment by abdullamu** [comment]
hum now i cant load any of my world its so random so annoying i hope it will be fixed soon have u tried MFR alpha builds ?

**Comment by Zarkazm** [comment]
No I haven't...didn't know there were alpha builds!

**Comment by abdullamu** [comment]
yup i did and now works better with all mods updated so try that from curseforge and check maybe the acually fixed it in one of the alphas

**Comment by skyboy** [comment]
It's not an MFR issue, though it may be a fundamental Thaumcraft issue: MFR assigns aspects to its items and they inherit aspects from parent items.
Thaumcraft will attempt to generate aspects for any items that are missing aspects in the crafting tree, and normally succeeds without problem. MFR also does this very late in the loading phase to deal with issues with load order that were previously causing thaumcraft to generate bizarre aspects on items.
