### ISSUE TITLE
Stack size issues with Plastic Sheets

### ISSUE THREAD

**Issue by WalterWeight** [skyboy/MineFactoryReloaded#449]
I'm having problems with plastic sheets seeming to exceed the 64 item stack limit.

Playing in survival on a multiplayer server, I can reproduce this over and over with a mod pack I'm putting together that features MFR 2.8.0-104, however because I started doubting my modpack, I've rebooted my PC, performed a clean installation of FTB Infinity 1.5.1 via the Curse client (I'm not using this for my own modpack), which uses the same version of MFR that I'm using (2.8.0-104), and I can repeat the issue in FTB Infinity too (in creative in a brand new world).

With nothing other than vanilla items in my inventory, say I have a stack of 64 plastic sheets on my hotbar, and a further 32 in my inventory, if I shift click the 32 items, I end up with a stack of 96 items on my hotbar. The same in reverse.

If I have 3 stacks of 32 items in my inventory, and double click them, I end up with a singe stack of 96 items attached to my mouse cursor (i.e. picked up from my inventory). If I try to place the stack, it places 64, and leaves the remaining 32 attached to my mouse cursor.

I've not extensively tested all MFR items, but I've tried a few other MFR items that I know should stack to 64, and they all behave fine. Plastic sheets are the only items that seem to be subject to this issue. I've also tried with some vanilla items, and they all behave fine.

Incidentally, the numbers above are quite arbitrary, I've reproduced this with various quantities of plastic sheets.

![This is a screenshot taken after shift clicking 32 items in my inventory, when I already have 64 items on my hotbar](https://cloud.githubusercontent.com/assets/1747010/7790155/d1d26c28-0274-11e5-8d2e-fb76dd557161.png)

**Comment by skyboy** [comment]
Plastic sheets can stack above 64. This is not a bug.
