### ISSUE TITLE
crash with MFR and Thaumcraft problem found

### ISSUE THREAD

**Issue by BigD999** [skyboy/MineFactoryReloaded#455]
In the Thaumcraft.class file in modhelpers there is an aspect that is not in Thaumcraft but added by magic bee's

 parseAspects2(Machine.Chronotyper, "3 tempus, 3 bestia, 5 machina, 3 sensus"); 

This crash dose not happen with magic bee's installed

**Comment by skyboy** [comment]
This is not a problem, my aspecting code automatically detects aspects which do not exist and does not add them.
