### ISSUE TITLE
Fatal Crash upon loading world! Makes world unplayable

### ISSUE THREAD

**Issue by andrewlalis** [skyboy/MineFactoryReloaded#458]
Every time my world is loaded, I crash after about 1 second. Here's the pastebin: http://pastebin.com/4JFHqVYf  Please help, since this makes my survival world unplayable. I looked into other instances of this type of crash, and I'm pretty sure that Minecraft is trying to render a block with an invalid data value.

**Comment by KristjanKr** [comment]
is it latest MFR? looking at your modslist then there sure are some old mods, also try newest forge? as i am running my world with mfr without any problems on latest forge.

**Comment by andrewlalis** [comment]
It is probably due to an old forge version, but this fatal error hasn't happened on all the worlds I play on, which is mysterious. However, I will update, and that most likely will fix it.

**Comment by skyboy** [comment]
Appears to be an issue with how older forge versions handled certain types of errors, causing world corruption. MFR unrelated.
