### ISSUE TITLE
Weird Rubber Tree Crash

### ISSUE THREAD

**Issue by murapix** [skyboy/MineFactoryReloaded#459]
http://pastebin.com/pvNA1H9p

I was looking at my map when the game crashed, telling me the rubber tree leaves had an out-of-bounds exception. I diidn't interact with them at all.

**Comment by jermangarc** [comment]
Did you remove any mods prior to this error?

**Comment by murapix** [comment]
Nope, nothing in my modpack was changed any time close to this error.

**Comment by jermangarc** [comment]
When you say "any time close to this error", how long ago was there a change? Is this happening on an existing map or new map? If on an existing map, was any mod removed since it's creation and then later reinstalled?

**Comment by jermangarc** [comment]
This type of error can come up weeks or months later even if you haven't changed a mod in a while.

**Comment by murapix** [comment]
This was on an already existing world. I removed Dynamic Tanks about a month ago, when I updated most of the outdated mods in my pack. Nothing changed between then and this crash.

**Comment by skyboy** [comment]
Something changed the metadata of the leaves, some mods like to arbitrarily change information about blocks, or otherwise generate blocks from other mods without regard as to if it's safe to do so.
