### ISSUE TITLE
PRC memory card stores directions as NSEW insted of LRFB

### ISSUE THREAD

**Issue by NolanSyKinsley** [skyboy/MineFactoryReloaded#461]
The PRC memory card stores the direcions as cardinals instead of relative to the placement of the PRC.

 This causes programs to change their outputs when copied to a PRC facing a different direction.

**Comment by skyboy** [comment]
Fixed by https://github.com/skyboy/MineFactoryReloaded/commit/02d60f3821c60845d18651ed2ca5fc7e1db8f0db
