### ISSUE TITLE
Dimension Manager Crash on World Loading

### ISSUE THREAD

**Issue by exiledalchemist** [skyboy/MineFactoryReloaded#470]
When installing MFR 2.8.1B1 build 121 and up I keep getting the same crash log about the dimension manager. However using MFR 2.8.1B1 build 113 does not have this issue. Here is the pastebin for that error log: http://pastebin.com/704JfEt9

**Comment by SvEgiiVEteR** [comment]
An error occurred again on 2.8.1B1-123
http://paste.ubuntu.com/11911856/

**Comment by skyboy** [comment]
Build 123 was made 24 hours before I made the commit closing this.
