### ISSUE TITLE
[Suggestion] Additional alloys

### ISSUE THREAD

**Issue by abculatter2** [skyboy/MineFactoryReloaded#471]
I suggest adding 3 new alloys, mainly as intermediaries to allow the production of Signalum, Enderium, and Lumium.
Namely, Stirling Silver (3 copper + 1 silver), which can then be transposed with destabilized redstone for Signalum. Additionally, this could be used as a replacement of copper in many recipes, which allows replacing a portion of the copper cost with silver.
Silver Pewter, (2 or 3 tin + 1 silver) which can be transposed with energized glowstone for lumium or combined with a Shiny ingot for Shiny Pewter. Silver Pewter, similarly to Stirling Silver, could be used as a tin replacement in many recipes.
Shiny Pewter would be pulverized and transposed with Resonant Ender for Enderium Blend.

I know i brought this up on IRC, but i just wanted to get a more official word on this. Apologies if it's annoying.

**Comment by skyboy** [comment]
MFR adds plastic. The response is the same: You're not getting a plastic plastic alloy any more than you're getting these alloys.
