### ISSUE TITLE
Still some machine doesn't connecting Buildcraft pipes. and some are doesn't work.

### ISSUE THREAD

**Issue by PrimaryC** [skyboy/MineFactoryReloaded#472]
I've checked #374, but there is not only just visual disconnection, but doesn't work machines

For example, sewer is just visual problem. sewage fluid have pulling out very well.

But slaughterhouse can't connect kinesis pipes both visual and actual.

can you fix it? plz

my versions are below
MC 1.7.10
forge-1.7.10-10.13.4.1448
buildcraft-7.0.17
buildcraft-compat-7.0.9
CoFHCore-[1.7.10]3.0.3-303
MineFactoryReloaded-[1.7.10]2.8.0-104

and may have some causes, other using mods are below
magicalcrops-4.0.0Beta5 and MFR Compat 1.2.1
Optfine 1.7.10 HD U C1
NEI 1.0.3.74

**Comment by skyboy** [comment]
Having checked all my code, these errors are with BuildCraft.
