### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MySt1k** [skyboy/MineFactoryReloaded#476]
LOG: http://pastebin.com/Dd0CZgfs
CRASH: http://pastebin.com/b0K4bm6h

MineFactoryReloaded-[1.7.10]2.8.1B1-125

**Comment by skyboy** [comment]
As demonstrated by this: ` java.lang.ClassCastException: crazypants.enderio.machine.spawner.TilePoweredSpawner cannot be cast to crazypants.enderio.machine.killera.TileKillerJoe`
MFR is not the only mod crashing with nonsense errors. Your world is corrupt.
