### ISSUE TITLE
Harvester not working on server, latest MFR

### ISSUE THREAD

**Issue by KristjanKr** [skyboy/MineFactoryReloaded#480]
So i made a small tree farm, with spruce saplings, planter works mine.. plants and does what it has to, but harvester is doing absolutely nothing, i mean it's not stuck on idle, it doesn't have sludge inside it, but it just won't harvest that big 2x2 spruce tree.

MFR:MineFactoryReloaded-[1.7.10]2.8.1B1-129
Forge:1492 both on server and on client.

**Comment by skyboy** [comment]
Harvesters do harvest spruce trees, make sure the tree is in range, and the harvester is facing the right way.
