### ISSUE TITLE
Harvester not working on server, latest MFR(repost)

### ISSUE THREAD

**Issue by KristjanKr** [skyboy/MineFactoryReloaded#481]
Latest forge 1492, latest MFR build 130, harvester is definitely in range, and it is actually touching the spruce log, and it just does not want to harvest it ( Playing on server ).

**Comment by KristjanKr** [comment]
Build 131 also affected.

**Comment by skyboy** [comment]
And this is still definitely not an issue. The harvester works on vanilla spruce wood. It happily harvests both in and out of dev without other mods.
