### ISSUE TITLE
Crash with Forestry and MFR Harvester

### ISSUE THREAD

**Issue by IdleGandalf** [skyboy/MineFactoryReloaded#483]
I got the following crash while using a Harvester with latest MFR and forestry 3.6.4 & 3.6.6.

~~I'm going to test later if it occurs with Forestry 3.6.6 too, but I didn't read something in the changelogs of forestry related to this.~~
This happens with latest (3.6.6) Forestry too.

http://hastebin.com/ocobuvolor.coffee

**Comment by skyboy** [comment]
Fixed by 179223ce793f1fac2450658c81616e8a4b72e9f4
