### ISSUE TITLE
incompatibility?

### ISSUE THREAD

**Issue by SvEgiiVEteR** [skyboy/MineFactoryReloaded#484]
http://pastebin.com/kCYuaWsU
there is any incompatibility?
that interestno crash occurs if you update the world mode
OpenBlocks-1.7.10-1.4.4-snapshot-668.jar
OpenModsLib-1.7.10-0.8-snapshot-396.jar
OpenEye-0.6-1.7.10-snapshot-145.jar
to the snapshot.
or set RFTools

**Comment by skyboy** [comment]
Your world seems to be corrupt.
