### ISSUE TITLE
[Enhancement] Ability to offset idle timers

### ISSUE THREAD

**Issue by mikeloeven** [skyboy/MineFactoryReloaded#490]
I ran into an issue with a vet system in that i had a situation where i needed two vets to keep the target creature alive under specific circumstances but the issue i had was that while it is possible to place two vets in such a way that their cycles are offset as soon as you move far enough away from the chunk they re-sync which results in the mob not being healed enough and dying. 
What is needed is the ability to specify an offset for machine cycle timers for instances where you need two machines supporting each other to perform a operation

**Comment by skyboy** [comment]
Or I just save the idle timer. It'll probably reduce overall server load anyway.

**Comment by mikeloeven** [comment]
So after this commit the machines will no longer reset their offset states when you leave the chunk ?
