### ISSUE TITLE
[Suggestion] Remove stained glass

### ISSUE THREAD

**Issue by Xen1290** [skyboy/MineFactoryReloaded#495]
Currently is useless, vanilla has already stained glass. Also Forestry has done the same thing. Maybe keep only the recipes with vanilla blocks, I can't see any uses for that glass. 
@skyboy 
https://github.com/ForestryMC/ForestryMC/issues/809

**Comment by Adaptivity** [comment]
#196

**Comment by Xen1290** [comment]
Oh, sorry, I haven't checked the other issues.
