### ISSUE TITLE
Config options to disable mod integration

### ISSUE THREAD

**Issue by Adaptivity** [skyboy/MineFactoryReloaded#502]
@skyboy can you add config options to specifically disable any mod integration? So, if I want I can disable Thaumcraft integration and etc.

**Comment by skyboy** [comment]
You can use `fmlModState.properties` in the config dir to enable/disable MFR's child mods.
ex:
```
MineFactoryReloaded|CompatThaumcraft=false
```

Even going so far as to disable `MineFactoryReloaded|CompatVanilla`
