### ISSUE TITLE
your mod broke in last forge 10.13.4.1540

### ISSUE THREAD

**Issue by loordgek** [skyboy/MineFactoryReloaded#503]
your mod broke in last forge 10.13.4.1540
http://paste.ee/p/tfvlN

**Comment by Oxosorrel** [comment]
What makes you think its MFR?

When on line 871 it states "[16:28:40] [Client thread/ERROR] [FML]: Caught exception from Avaritia"

And the error log continues to blame Avaritia... did something indicate to you it it was MFR that did this?

**Comment by loordgek** [comment]
[16:28:40] [Client thread/ERROR] [FML]: Caught exception from MineFactoryReloaded
java.lang.NullPointerException
those mods are in it 
Avaritia Forestry (Botany ExtraTrees those are binnie mods) harvestcraft MineFactoryReloaded ExtraTiC

**Comment by loordgek** [comment]
http://paste.ee/p/qBJaJ forge build 1541

**Comment by skyboy** [comment]
Fixed by https://github.com/CoFH/CoFHLib/commit/78801622259603b668954a06f1030f5c3385ee75
