### ISSUE TITLE
Cofh core bug

### ISSUE THREAD

**Issue by XxZajoZzO** [skyboy/MineFactoryReloaded#505]
I got this few seconds after lauchibg minecraft: http://imgur.com/rWBIKfZ
Log says: [11:41:41] [Client thread/ERROR] [FML]: The mod MineFactoryReloaded (MineFactory Reloaded) requires mod versions [CoFHCore@[1.7.10R3.1.0B1,1.7.10R3.2.0)] to be available.
MFR wants cofh core 3.1.0 B1 and latest version on curse is 3.0.4 B1-308.
MFR: MineFactoryReloaded-[1.7.10]2.8.1B1-153

**Comment by Tsunayoshi** [comment]
I have the same problem with: MineFactoryReloaded-[1.7.10]2.8.1B1-154

So this here is closed, what was the solution?

Error Msg: minimum required COFHcore 1.7.10R3.1.0B1,1.7.10R3.2.0
There is no 3.1 version of CoFHCore on Curse. Only 3.0.x
