### ISSUE TITLE
[Suggestion/Request] Fruit Picker and mana beans

### ISSUE THREAD

**Issue by lengeltjes** [skyboy/MineFactoryReloaded#507]
Because the Mana beans from Thaumcraft are probably written as a subclass from Cocoa beans, they can be farmed automatically using a Fruit Picker and a Planter. Can this be disabled by default or can there be a config option to disable this?

**Comment by skyboy** [comment]
See https://github.com/skyboy/MineFactoryReloaded/issues/502
