### ISSUE TITLE
[Issue] Auto Anvil Cannot Repair/ Enchant Some Modded Items That Will Work With Vanilla Anvils

### ISSUE THREAD

**Issue by mikeloeven** [skyboy/MineFactoryReloaded#508]
The Auto Anvil needs to be more aggressive when it comes to detecting repair/ enchant operations for modded items. I have frequently encountered situations where operations that can be performed on a vanilla anvil will not work with the auto anvil.

Several Examples include Reparing armors and weapons made from a various modded materials

Applying Enchantments to armors and weapons made from various modded materials

Tuning Enderio Powered Spawners  

While not all modded weapons and armor can be repaired in an anvil there are plenty of these items in the FTB packs that can be Repaired / Enchanted using a vanilla anvil while the auto anvil will refuse to accept the required materials to perform the desired function

**Comment by skyboy** [comment]
I thought there was an issue about this already, but appears not. It's been fixed in-dev.
