### ISSUE TITLE
[REQUEST/SUGESTION] Add compatibility Small Meat/Large Meat/Sirloin from Digimobs

### ISSUE THREAD

**Issue by AlejaKaiser** [skyboy/MineFactoryReloaded#511]
Hi, Im not sure if I'm writing right because the english isnt my language. In Digimobs, we had to harvest Meat for it in the same way like wheat. I request a way to automatizate this, so please, add compatibility with this mod.

Thanks a lot.

**Comment by asl97** [comment]
it may not be my place to say this but considering that [there is an api for adding it](https://github.com/skyboy/MineFactoryReloaded/blob/0deaf61c3ff3c4ac2f6bd158503967fe24befb73/src/powercrystals/minefactoryreloaded/api/IFactoryHarvestable.java) and Digimobs is close source, they should be the one adding the support.

**Comment by skyboy** [comment]
Indeed, if they want those things to be automatable, I provide an extensive API.
