### ISSUE TITLE
Harvester crashes game when harvesting Forestry trees

### ISSUE THREAD

**Issue by TehStoneMan** [skyboy/MineFactoryReloaded#513]
Using a MineFactoryReloaded harvester to farm Forestry trees causes a crash

[crash-2015-11-29_17.57.40-server.txt](https://github.com/skyboy/MineFactoryReloaded/files/46522/crash-2015-11-29_17.57.40-server.txt)

**Comment by skyboy** [comment]
Fixed by https://github.com/skyboy/MineFactoryReloaded/commit/0fb118f4cdbb076c5afc9ba71839739ba9f8e20d
