### ISSUE TITLE
pretty big bug, never even seen one like this before, maybe ASM related

### ISSUE THREAD

**Issue by plaguewolf** [skyboy/MineFactoryReloaded#518]
reposting here, as reference in case its mfr thats causing it

instance setup;

latest recommended forge [1558]

technomancy 0.12.2
minefactoryreloaded 2.8.1B1-160
[required for MFR]
cofhcore 3.1.0B1-321
thermal dynamics 1.1.0-161
thermal expansion 4.1.0B1-234
thermal foundation 1.2.1-109

error: http://pastebin.com/TBh8kDP4

related entries;
https://github.com/theflogat/Technomancy/issues/174

**Comment by plaguewolf** [comment]
it is, in fact, MFR, thats causing it, as rolling back to my older version it loads

working on MFR 2.8.1B1-131

testing all version after that in revers order to determine what change broke things

**Comment by plaguewolf** [comment]
k, so, working back from latest, ive determined that whatever changes you made from version;

working on MFR 2.8.1B1-136 <- works
to
working on MFR 2.8.1B1-137 <- does not work

**Comment by skyboy** [comment]
The change i made in build 137 (on oct. 14th) was to change the target version of java from 1.6 to 1.7.

The error is in https://github.com/theflogat/Technomancy/blob/master/src/main/java/theflogat/technomancy/asm/TechnomancyCoreTransformer.java#L31
