### ISSUE TITLE
MFR Recipes not syncing SMP

### ISSUE THREAD

**Issue by jburrows82** [skyboy/MineFactoryReloaded#527]
MFR 2.8.1B1-168
Forge 1614

The configuration settings which select which variation of recipes to register (Vanilla/Thermal Expansion/EnderIO), doesn't seem to sync to the client when connecting to a server. I ran across this when resetting all configs on the server and the Thermal Expansion recipe was enabled, but the clients had Vanilla enabled. The clients saw the Vanilla recipes, appeared to be able to use the vanilla recipes, but could not pull the MFR machines out of the crafting table.

I reversed the server to Vanilla recipes then the clients to Thermal Expansion recipes to see if the issue persisted or if it was just one corner case. Same issue. Once the local and remote config setting matched, things worked as expected.

Surely the server should be able to force which recipe the client registers, correct?

**Comment by skyboy** [comment]
Configs always have to be the same on server and client to ensure uniform behavior.
