### ISSUE TITLE
[Crash] Server crash using PRC

### ISSUE THREAD

**Issue by frenchiveruti** [skyboy/MineFactoryReloaded#529]
[crash-2016-01-14_21.40.11-server.txt](https://github.com/skyboy/MineFactoryReloaded/files/91213/crash-2016-01-14_21.40.11-server.txt)

**Comment by skyboy** [comment]
Probably related to #528

**Comment by frenchiveruti** [comment]
I'm sure it was a completely different error, because this time it didn't have any upgrades placed on the PRC
