### ISSUE TITLE
Thermal Expansion Fluid Transposer (bucket to bottle)---MFR?

### ISSUE THREAD

**Issue by apdjz** [skyboy/MineFactoryReloaded#531]
I was wondering if there was a solution.

CoFH/Feedback#805

**Comment by skyboy** [comment]
Does this still occur in the latest versions?

**Comment by apdjz** [comment]
MineFactoryReloaded-[1.7.10]2.8.0-104.jar is the version I have. Correct me if i am wrong, but i think this is the newest

**Comment by skyboy** [comment]
You are wrong.

**Comment by apdjz** [comment]
Ah i see a new version. I will hopefully test this soon.
