### ISSUE TITLE
Laser Drill

### ISSUE THREAD

**Issue by ThePreviousOne** [skyboy/MineFactoryReloaded#534]
how do I add my ores to the Laser Drill? its not in the API so I am wondering do I use this?
public static void registerLaserOre(int weight, ItemStack ore) 
maybe I didn't look hard enough but I didn't see it being called anywhere.

**Comment by skyboy** [comment]
https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/api/FactoryRegistry.java#L24

**Comment by ThePreviousOne** [comment]
Cool Thanks
