### ISSUE TITLE
Self-sustaining infinite energy?

### ISSUE THREAD

**Issue by sc24evr** [skyboy/MineFactoryReloaded#535]
It seems you can create a closed loop infinite energy generator with no interaction need by using a Lava Fabricator and a Fluid Transposer to fuel a MFR Steam Boiler. It creates enough power to run four steam turbines as well as itself. I was just curious if this was an intended feature or a bug. See the following http://forum.feed-the-beast.com/threads/self-sustaining-closed-loop-lava-turbine-generator.142830/

**Comment by skyboy** [comment]
The default config for the lava fabrocator's cost in 2.8.1 is high enough to stop this. Existing configs for 2.8.0 and below have a lower cost however.
