### ISSUE TITLE
Fertilizer machine bug

### ISSUE THREAD

**Issue by Vanths** [skyboy/MineFactoryReloaded#536]
I've enocountered a bug in both the 8.0 and 8.1 versions of MFR, the fertilizer machine isn't working properly, it appears to be accepting the fertilizer(s), but not using them to grow the plants. I've tried IC2, forestry and MFR fertilizer versions and none work.

Additional info: The machine is accepting power just fine, the modpack I'm using is FTB Infinity version 2.3.5. which runs an older version of MFR, I've tried updating manually but the issue persists.

**Comment by skyboy** [comment]
The fertilizer works properly with all plants registered with it; which includes all vanilla plants. In 2.8.1 there is a config option to enable that will have it trying to auto-recognize other plants it can work on.
