### ISSUE TITLE
Can't create rancher in multiplayer

### ISSUE THREAD

**Issue by TheFamousPG** [skyboy/MineFactoryReloaded#538]
I use The 1.7.10 pack and I can't create rancher in mutliplayer.
The issue on 1.7.10 : https://github.com/EnderMediaDev/The-1.7.10-Pack/issues/1053

In solo : 
https://gyazo.com/6a3c42b03472acf6d00f6bb6301108e9

In multi 
https://gyazo.com/7a135420ce60182ee0a029349c9f485c

Server config
https://gyazo.com/3e29137b039d4360499c24e8976d84a5
https://gyazo.com/b3190d98583cd7bfed8be0c5acd5a1f4

**Comment by skyboy** [comment]
I expect whatever server you're on is using minetweaker to remove or alter the recipe.

**Comment by TheFamousPG** [comment]
It's on my own server. I don't use minetweaker.
