### ISSUE TITLE
laser drill randomly stops getting power

### ISSUE THREAD

**Issue by wackoamd1** [skyboy/MineFactoryReloaded#539]
so i have a laser drill surrounded by 4 prechargers.
when i place the prechargers and supply them power the laser drill shows 20K from the 4 prechargers but randomly it just shows 10K and i have to break all my prechargers before it gets back u to 20K.
i dont know if its just a graphics thing or that it really isnt getting power from 2 of the 4 prechargers randomly.
and it isnt a power issue ive got 2MEG incoming from a big reactor (yes thats 2MIL RF and the reactor isnt even full of fuel ;-) )

mc 1.7.10
MFR 2.8.1-174

its pretty annoying as i like to keepp my base neat and tidy so i hide everything in walls and floors

**Comment by skyboy** [comment]
The laser drill is working at full capacity, the amount you see stored in its buffer changes based on minecraft internal logic that's not the same from world load to world load.
