### ISSUE TITLE
FMLInterModComms problems

### ISSUE THREAD

**Issue by IceDragon200** [skyboy/MineFactoryReloaded#540]
Reading the [IMCHandler code](https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/IMCHandler.java#L120), I should be able to do this: 
```java
FMLInterModComms.sendMessage(modID, "registerHarvestable", new AppleFactoryHarvester());
```
and all would be well in the world.

Unfortunately, not so, forge has no overload for `Object` OR a visible `IMCMessage` (so I could send it manually), only `String`, `ItemStack` and `NBTTagCompound`, therefore, any code that would take arbitrary objects is essentially bricked by design.

Please do correct me if I'm missing something here, but how would I send a `IFactoryHarvestable` through the IMC if it won't accept the Objects through its interface?

**Comment by skyboy** [comment]
```java
FactoryRegistry.sendMessage("registerHarvestable", new AppleFactoryHarvester())
```
