### ISSUE TITLE
Crash with MFR and Practical Logistics

### ISSUE THREAD

**Issue by b0bst3r** [skyboy/MineFactoryReloaded#541]
Can you have a look at this crash please and advise/fix/work magic?

https://github.com/SonarSonic/Practical-Logistics/issues/34

**Comment by skyboy** [comment]
I can't do anything to stop other mods corrupting in-world blocks.

**Comment by AEnterprise** [comment]
@skyboy you can't prevent corruption but maybe a check that the meta isn't out of bounds so it stops crashing?
