### ISSUE TITLE
Unifier access with logistics pipes inconsistent

### ISSUE THREAD

**Issue by Benjamin-Berry** [skyboy/MineFactoryReloaded#542]
When using a crafting module in a chassis pipe with the Unifier it functions if the pipe is on the top or the bottom.

The weird part is if the pipe is on the side then it only recognizes when the player puts items into the unifier.

FTB Infinity 2.3.5
https://github.com/RS485/LogisticsPipes/issues/937

**Comment by skyboy** [comment]
The [unifier](https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/tile/machine/TileEntityUnifier.java#L133) does not exhibit any [sidedness](https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/tile/machine/TileEntityUnifier.java#L208-L217): all sides are valid inputs and all sides are valid outputs, and all inventory changes will inform everything nearby.
