### ISSUE TITLE
Crash after updating MFR

### ISSUE THREAD

**Issue by Keyarose** [skyboy/MineFactoryReloaded#543]
Hello, I'm getting a crash during startup after updating MFR.
Crash Log: http://pastebin.com/7zpryck5

Version Updated to: 2.8.1-174
Version Updated from: 2.8.0-104

**Comment by skyboy** [comment]
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/518

**Comment by Keyarose** [comment]
Updating Technomancy fixed it for me, thanks for pointing me that way.
