### ISSUE TITLE
reopen 539 pls

### ISSUE THREAD

**Issue by wackoamd1** [skyboy/MineFactoryReloaded#544]
i just tested it with a big reactor and 4 laser drills with 4 prechargers should pull 80k of rf however with the problem i described in 539. its not internal logic from mc.
the precharges actually are not pulling the 80k but only 40k thats exactly what im seeing in my laser drill. only 2 precharger working ( eventhough they show that they are sending 5k ) instead of 4 per drill so instead of 20k per drill it only pulls 10k per dril (like it shows) and thats what im seeing in de bigreactor.

**Comment by skyboy** [comment]
After checking the code and verifying in-world, prechargers do work correctly. If they are not transmitting energy for you they are facing the wrong way, or there is a block obstructing their view of the laser drill.
