### ISSUE TITLE
EnderIO Compatibility Issue

### ISSUE THREAD

**Issue by Keyarose** [skyboy/MineFactoryReloaded#545]
The EnderIO Item Conduit is no longer connecting to the MFR Rancher.  It still connects to other machines such as the Harvester.

MFR version: 2.8.1-174
EIO version: 2.3.0.424_beta
![2016-03-20_15 29 04](https://cloud.githubusercontent.com/assets/1906772/13906267/f4549ad6-eeb0-11e5-9d6e-611155b26a6c.png)

**Comment by skyboy** [comment]
Do other mods exhibit the same problem?

**Comment by Keyarose** [comment]
Not as far as I can tell, all other machines I use with the Item conduit are still working.

**Comment by skyboy** [comment]
Mods, not machines. Buildcraft, ThermalDynamics, Mekanism, etc.

**Comment by Keyarose** [comment]
Ah, sorry thought you were asking if there were other mod's machines having issues with the conduits.  I'll test some other item transport methods as soon as I can, I already know that vanilla chests work as expected.

**Comment by Keyarose** [comment]
So I checked some other mod item transport tubes.  Buildcraft and ThermalDynamics do not work and will not graphically connect to the Harvester; Mekanism will graphically connect but will not take items.
