### ISSUE TITLE
switch languages gets crash in MFR

### ISSUE THREAD

**Issue by alexeik** [skyboy/MineFactoryReloaded#546]
http://pastebin.com/XFup7yXm
here is crash dump
using latest beta and latest release i have the same behaviour.
i do switch from Russian to English and get this crash.

**Comment by skyboy** [comment]
Anything that would reload textures will cause this, another mod has one of MFR's fluids and is neglecting to register icons for it.

**Comment by alexeik** [comment]
what i must to do to exclude this error?
