### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Ar97x** [skyboy/MineFactoryReloaded#549]
https://www.dropbox.com/s/z8aemjwv1wylr43/crash-2016-03-28_18.07.14-client.txt?dl=0

Crashed on initialization. Seems like MFR is the one causing the crash so I brought it to your attention. I'm using the latest version (2.8.1-174) and I've tried out before with the previous one (2.8.0-104), both crashed.

**Comment by skyboy** [comment]
You have enabled ThermalExpansion recipes, but do not have ThermalExpansion.
