### ISSUE TITLE
Deep Storage Unit/Logistics Pipes bug

### ISSUE THREAD

**Issue by firelizzard18** [skyboy/MineFactoryReloaded#553]
Scenario: DSU locked to Pulverized Silver but containing nothing; one one side a Mk II Chassis with a Provider Module (default settings) and ItemSink Module (default settings other than sinking Pulverized Silver).

Result: When silver enters the system, it gets routed to the DSU via the chassis with the itemsync (visually verified) and the silver disappears from the pipe into the DSU. But the silver just kind of vaporizes. The DSU does not add it to the inventory.

I also tried this with Pulverized Tin. I'm assuming it's a general bug. If there was even a single silver/tin in the output slot, it works. But with a count of 0 and nothing in the output slot, the silver is lost.

**Comment by skyboy** [comment]
I've gone over my code, AE's code, and LP's code, can't find a reason for this, and checked that items aren't deleted via regular insertion.

Are the items being deleted, or is the item going to the output slot? The DSU doesn't show the stack size of the output slot as part of the "count," as the count is the quantity of items hidden from view inside the DSU.
