### ISSUE TITLE
MFR Spawning entities with inventories (dupe)

### ISSUE THREAD

**Issue by Eufranio** [skyboy/MineFactoryReloaded#555]
I found an dupe, MFR is spawning entities even if it contains items.

https://github.com/aidancbrady/Mekanism/issues/3208

EDIT: Maybe put an config to disable COMPLETELY exact copy?

**Comment by skyboy** [comment]
Several things wrong in that issue: First, zombies that are exact-copied do not drop anything their "real" counterpart picked up or was wearing.

Second: An API is provided to blacklist (via IMC, which is recommended for things like the robots here) entities, and another is provided to allow other mods to erase the contents of mob's inventories when exact-copied when applicable (as is done with [horses](https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/farmables/spawnhandlers/SpawnableHorse.java) and [endermen](https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/farmables/spawnhandlers/SpawnableEnderman.java)).

Third, a configuration-based blacklist is also provided for specific modpacks to prevent such issues.
