### ISSUE TITLE
Bug in EnderIO chunkloader crafting

### ISSUE THREAD

**Issue by MineWitherMC** [skyboy/MineFactoryReloaded#557]
https://github.com/powercrystals/MineFactoryReloaded/issues/442
These deprecated capacitor banks are not craftable. Tested with MFR 174 and 104 and EnderIO beta 2.3.0.422 and even 2.2.8.387, please fix.

**Comment by bookerthegeek** [comment]
Why open another issue? This is a duplicate.  Please close and continue with original issue.
