### ISSUE TITLE
[SUGGESTION] Heated liquids input for Steam Boiler

### ISSUE THREAD

**Issue by Ar97x** [skyboy/MineFactoryReloaded#559]
Hi, I would love to see a new feature to the steam boiler: be able to input hot fluids (lava, mostly) directly inside the Machine. This would make many lives easier, because the provided lava input (through buckets) is kinda hard to make, and I don't think it's possible without other mods like Thermal Expansion.

**Comment by skyboy** [comment]
Liquid fueling is a bit beyond scope for the device.

**Comment by Ar97x** [comment]
:( Lame, I thought that you could make an liquid fuel input side for the machine, but that's alright.
