### ISSUE TITLE
Laser Drill entries for ReactorCraft Fluorite Ore

### ISSUE THREAD

**Issue by condensedapple** [skyboy/MineFactoryReloaded#560]
The ores of Reika's ReactorCraft have reasonable and IMO appropriate weights and color codes (laser foci) in the MFR Laser Drill **except** Fluorite Ore, which is messed up (Blue Fluorite has a white code, the other ones arent even registered). Blue Fluorite has a weight of 20, which results in my modpack in a chance of 0.76%.
It would be nice if the other Fluorite Ores could also have a MFR Laser Drill entry by default. Currentely I use the following MineTweaker/ModTweaker code to accomplish that result:
```
mods.mfr.MiningLaser.removePreferredOre(8, <ReactorCraft:reactorcraft_block_fluoriteore>);
mods.mfr.MiningLaser.addPreferredOre(11, <ReactorCraft:reactorcraft_block_fluoriteore>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:1>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(6, <ReactorCraft:reactorcraft_block_fluoriteore:1>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:2>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(1, <ReactorCraft:reactorcraft_block_fluoriteore:2>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:3>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(2, <ReactorCraft:reactorcraft_block_fluoriteore:3>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:4>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(13, <ReactorCraft:reactorcraft_block_fluoriteore:4>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:5>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(14, <ReactorCraft:reactorcraft_block_fluoriteore:5>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:6>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(0, <ReactorCraft:reactorcraft_block_fluoriteore:6>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:7>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(4, <ReactorCraft:reactorcraft_block_fluoriteore:7>);
```
An appropriate handling in https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/modhelpers/vanilla/Vanilla.java could be necessary.

This has also been reported to [ReactorCraft](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/869).

**Comment by skyboy** [comment]
MFR's auto-recognition is just pulling whatever it finds first in the oredict, if these ores are not all the same then I should remove that entry.

**Comment by condensedapple** [comment]
well, then it is reikas job to register his Fluorite Ores if he wants to do this (is it possible with IMC?)

**Comment by skyboy** [comment]
Yes.

**Comment by ReikaKalseki** [comment]
Is the color a string (and if so, in what format)? An int (and if so, dye meta, wool meta, RGB...)? Something else?

**Comment by skyboy** [comment]
It's an int and I need to go through my API's documentation and clarify data types.

I believe the values are the same as wool, but here's the listing:

```javascript
black = 15;
red = 14;
green = 13;
brown = 12;
blue = 11;
purple = 10;
cyan = 9;
silver = 8;
gray = 7;
pink = 6;
lime = 5;
yellow = 4;
lightBlue = 3;
magenta = 2;
orange = 1;
white = 0;
```

**Comment by condensedapple** [comment]
Thanks a lot.
