### ISSUE TITLE
Urgent - Empty Deep Storage Unit deletes AE items - similar to issue #553

### ISSUE THREAD

**Issue by drekryan** [skyboy/MineFactoryReloaded#565]
I ran into an issue that is similar to issue #553 while playing SkyFactory 2.5.2

I have an ME System with one Drive Bay connected to the controller and an array of DSU's connected with a ME Interface priority of 1. These Deep Storage units are holding no items and are connected to the network using ME Storage Buses. When I insert an item into my ME System it attempts to place them into the DSU's as the priority is 1. Regardless of whether the DSU is locked or unlocked if the DSU is not configured with an item already the item will be deleted. An unlocked DSU with a priority of 1 on the network will not try to take the item. Likewise a locked DSU will not take the item (like it should) but it also causes the item to be lost and does not force the ME System to put it on the ME Drives with a lower priority. The DSU should not attempt to take the item if the DSU is locked with no items. The DSU should take any item it can if it is unlocked. Finally a locked DSU with an item should only attempt to take the item already inside the DSU. DSU's SHOULD NOT delete items.

@skyboy

**Comment by AnrDaemon** [comment]
Do you have     S:MineFactoryReloaded=AUTO or any other setting?
May be try turning it off on a copy of the world. Supposedly, DSU's also expose regular storage provider for things that do not understand their depths.
