### ISSUE TITLE
Not an issue more a question

### ISSUE THREAD

**Issue by Xireka** [skyboy/MineFactoryReloaded#566]
I was actually just wondering, what are the changes in the regularly released alpha versions of MFR?

Is it big changes or fixes? Should I update to them or is it very unstable to do so?

I just can't seem to find a change log or any information anywhere (sorry for my clumsiness) :( so I thought I'd simply ask here.

**Comment by skyboy** [comment]
Changes on the alpha builds are whatever was [commited](https://github.com/skyboy/MineFactoryReloaded/commits/master) in the hour prior to their release - they're built and uploaded automatically.

**Comment by Xireka** [comment]
Oh okay thanks for the info, so since they sometimes add world corruption I'm guessing it's better to stay with the stable version for now? :)
