### ISSUE TITLE
MineFactoryReloaded-[1.7.10]2.8.2B1-196

### ISSUE THREAD

**Issue by Markezzz** [skyboy/MineFactoryReloaded#572]
Hey skyboy,
since you released MineFactoryReloaded-[1.7.10]2.8.2B1-196 i need CoFHCore version 1.7.10R3.1.3B1 or 1.7.10R3.2.0. But their is no download for this version.

Can you give us a download link for the beta from cofhcore?

Thx for your answer. :)

**Comment by skyboy** [comment]
When it's available it'll be on curse, like all alphas/betas.
