### ISSUE TITLE
Update to 1.10.2!!

### ISSUE THREAD

**Issue by MCrafterzz** [skyboy/MineFactoryReloaded#573]
Please do it, I want to be able to have this great mod in newer minecraft versions

**Comment by skyboy** [comment]
Unless your intent is to hire me to get it done, then you'll just have to wait until I have the time necessary to get everything updated.

**Comment by Aterne** [comment]
How much are we talking about ? And would I get the some rights for the 1.10.2 Version ?

**Comment by djcprone** [comment]
I'd donate to this.
