### ISSUE TITLE
Block Placer duplication

### ISSUE THREAD

**Issue by phill3** [skyboy/MineFactoryReloaded#585]
A contraption like so with a block placer, a block breaker from any mod and a redstone torch leads to blocks being duplicated. [https://images-ext-2.discordapp.net/eyJ1cmwiOiJodHRwczovL3B1dS5zaC9wV2xEeS81NjkyNTU5OGE5LmpwZyJ9.vcNcB9uAYnEkEcqA3A1Jxg1wa3o](image)

**Comment by skyboy** [comment]
Same as https://github.com/skyboy/MineFactoryReloaded/issues/444 but for whatever mod that block breaker is from.
