### ISSUE TITLE
Crash when leaving a sewer system, harvester, Fertilizer and a sludge boiler active and going outside chunk boundary. 

### ISSUE THREAD

**Issue by Akitori** [skyboy/MineFactoryReloaded#586]
[crash-2016-12-10_22.11.47-server.txt](https://github.com/skyboy/MineFactoryReloaded/files/644226/crash-2016-12-10_22.11.47-server.txt)

**Comment by skyboy** [comment]
This is most likely related to https://github.com/skyboy/MineFactoryReloaded/commit/25fd5f866bbd0dd72134004e054ca245e066cc62
