### ISSUE TITLE
Latest MFR Version Doesn't load

### ISSUE THREAD

**Issue by Joshwoo70** [skyboy/MineFactoryReloaded#588]
Gist : https://gist.github.com/Joshwoo70/435359192e0cd2e58b029eb790f57e95

Edit : version 201 of MFR Seems to be broken as Servers nor clients read them, Link to File in question : https://minecraft.curseforge.com/projects/minefactory-reloaded/files/2366149

**Comment by unitedgamer6** [comment]
can confirm this as well, when i add MFR to my mods folder and launch it shows "63 mods loaded, 53 mods active" but when i remove the mod and launch shows "53 loaded, 53 active" any fix for this in the working?
