### ISSUE TITLE
MineFactory for 1.10.2

### ISSUE THREAD

**Issue by Aterne** [skyboy/MineFactoryReloaded#590]
Hello, 
I saw that someone asked for a 1.10.2 support and  you said that you wouldnt do 
it until someone hires you to do so. So how much would it take?

**Comment by bookerthegeek** [comment]
Lets see....

Professional programming is about $150 an hour, say it would take about a week straight to update the mod....  So about $9000 for the mod to update if you wantted to pay for it.


And no you would be purchasing his time, not the mod so all you would get is the warm fuzzy you helped a swell guy out.

**Comment by tangalbert919** [comment]
That's a bummer. Unless anyone were willing to pay @skyboy to do any work, he won't work on the mod.
Someone else has been doing 1.10.X support lately. Just check the network graphs and follow the really long time that has a lot of points on it.

**Comment by skyboy** [comment]
Solved by d8e484865bc7a55cb7b5eb5c70b2d96f3c0b588f
