### ISSUE TITLE
MFR 1.10.2 Crash during Launch

### ISSUE THREAD

**Issue by AnthonyKane5528X** [skyboy/MineFactoryReloaded#593]
CofH Core:  1.10.2-4.4.1.7
MFR:  [1.10.2]2.9.0B1-215
Forge: 12.18.3.2254

pastebin:
https://pastebin.com/rnFrh1fR

What happens:
-Install MFR for 1.10.2.  Attempt to launch game using Twitch/curse launcher.  Game crashes.
-Remove MFR, attempt launch, game loads, everything works.

What I expect to happen:
-Install MFR for 1.10.2.  Attempt to launch, game should load.

**NOTE**  in overview for the mod it says you need CofH 1.7+  I do not know what this means and assumed it was a typo leftover from when MFR was for 1.7.10.  Have no idea if this is what is causing the problem as there is no CofH for 1.10.2 that has a 1.7+ entry.

**Comment by bogger33** [comment]
Getting the same crash, same error. Also it doesn't say you need CoFH 1.7+, it says you need it for 1.7+, as in minecraft versions 1.7 and higher.

**Comment by Miner94** [comment]
https://github.com/Miner94/Crash-log/blob/master/README.md this is what i get

**Comment by skyboy** [comment]
Resolved by 087baed9c7090a1cb2e61389b8858eeeb456feac
