### ISSUE TITLE
Tessellating Block Error

### ISSUE THREAD

**Issue by blockbreaker1361** [skyboy/MineFactoryReloaded#594]
Got this crash before game fully loads in.
The game crashed whilst tesselating block model
The game crashed whilst tesselating block model
Error: java.lang.AbstractMethodError: powercrystals.minefactoryreloaded.block.BlockRubberLeaves$$Lambda$1516/1242522314.func_186720_a(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;I)I

**Comment by Miner94** [comment]
i Got this one dude help https://github.com/Miner94/Crash-log/blob/master/README.md

**Comment by Miner94** [comment]
just got the same thing

**Comment by Miner94** [comment]
java.lang.AbstractMethodError
	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:167)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:229)

**Comment by skyboy** [comment]
Fixed by 999526704ca756262cfc8e66d8c67da727d8eb5d
