### ISSUE TITLE
[1.10.2] Exception while ticking a block

### ISSUE THREAD

**Issue by Braayy** [skyboy/MineFactoryReloaded#596]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.4.7-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.5.136-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 16/06/17 23:17
Description: Exception while ticking a block

java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    cofh/asmhooks/world/WorldServerProxy.func_72970_h()Lnet/minecraft/world/chunk/IChunkProvider; @4: invokevirtual
  Reason:
    Type 'net/minecraft/world/WorldServer' (current frame, stack[0]) is not assignable to 'cofh/asmhooks/world/WorldServerProxy'
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'cofh/asmhooks/world/WorldServerProxy' }
    stack: { 'net/minecraft/world/WorldServer' }
  Bytecode:
    0x0000000: 2ab4 003a b603 c8b0                    

	at powercrystals.minefactoryreloaded.tile.machine.TileEntityGrinder.func_145834_a(TileEntityGrinder.java:80)
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:809)
	at net.minecraft.world.World.func_175690_a(World.java:2461)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785)
	at net.minecraft.world.World.func_175625_s(World.java:2402)
	at powercrystals.minefactoryreloaded.block.BlockFactoryMachine.getLightOpacity(BlockFactoryMachine.java:109)
	at net.minecraft.world.World.func_180500_c(World.java:2895)
	at net.minecraft.world.World.func_175664_x(World.java:2779)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.world.World.func_175698_g(World.java:381)
	at net.minecraftforge.fluids.BlockFluidClassic.func_180650_b(BlockFluidClassic.java:149)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:744)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
	at powercrystals.minefactoryreloaded.tile.machine.TileEntityGrinder.func_145834_a(TileEntityGrinder.java:80)
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:809)
	at net.minecraft.world.World.func_175690_a(World.java:2461)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785)
	at net.minecraft.world.World.func_175625_s(World.java:2402)
	at powercrystals.minefactoryreloaded.block.BlockFactoryMachine.getLightOpacity(BlockFactoryMachine.java:109)
	at net.minecraft.world.World.func_180500_c(World.java:2895)
	at net.minecraft.world.World.func_175664_x(World.java:2779)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.world.World.func_175698_g(World.java:381)
	at net.minecraftforge.fluids.BlockFluidClassic.func_180650_b(BlockFluidClassic.java:149)

-- Block being ticked --
Details:
	Block: thermalfoundation:fluid_redstone[level=7]
	Block location: World: (93,1,-1323), Chunk: (at 13,0,5 in 5,-83; contains blocks 80,0,-1328 to 95,255,-1313), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:744)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: Testes
	All players: 1 total; [EntityPlayerMP['Braayy'/33, l='Testes', x=98,21, y=2,00, z=-1322,85]]
	Chunk stats: ServerChunkCache: 272 Drop: 0
	Level seed: 3879931732944981598
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 3;minecraft:grass;1;village
	Level spawn location: World: (100,4,-1304), Chunk: (at 4,0,8 in 6,-82; contains blocks 96,0,-1312 to 111,255,-1297), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Level time: 22748 game time, 6801 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 31094 (now: false), thunder time: 157497 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 207781432 bytes (198 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D8 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	UCHIJAAAA	backpack{3.0.1} [Backpack] (backpack-3.0.1-1.10.2.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.10.22} [Chisel] (Chisel-MC1.10.2-0.0.10.22.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.9.267} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	UCHIJAAAA	cofhcore{4.1.4} [CoFH Core] (CoFHCore-1.10.2-4.1.4.7-universal.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHIJAAAA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.1.183} [Ender IO] (EnderIO-1.10.2-3.1.183.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.4.1.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.12.801} [Iron Chest] (ironchest-1.10.2-7.0.12.801.jar) 
	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJAAAA	Mekanism{9.2.2} [Mekanism] (Mekanism-1.10.2-9.2.2.301.jar) 
	UCHIJAAAA	MekanismGenerators{9.2.2} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.2.301.jar) 
	UCHIJAAAA	MekanismTools{9.2.2} [MekanismTools] (MekanismTools-1.10.2-9.2.2.301.jar) 
	UCHIJAAAA	minefactoryreloaded{2.9.0B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.10.2]2.9.0B1-216.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{2.9.0B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.10.2]2.9.0B1-216.jar) 
	UCHIJAAAA	reborncore{2.13.5.136} [RebornCore] (RebornCore-1.10.2-2.13.5.136-universal.jar) 
	UCHIJAAAA	quantumstorage{3.3.2} [QuantumStorage] (QuantumStorage-1.10.2-3.3.2.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.5.136} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.13.5.136-universal.jar) 
	UCHIJAAAA	thermalfoundation{2.1.1} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.1.3-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.1.3} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.3.4-universal.jar) 
	UCHIJAAAA	thermaldynamics{2.0.4} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.4.6-universal.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.4.7-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
RebornCoreASM (RebornCore-1.10.2-2.13.5.136-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  team.chisel.common.asm.ChiselTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	minefactoryreloaded: -[1.10.2]2.9.0B1-216
	CodeChickenLib Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                  * An unsupportted RF API is installed (1.7.0 from (guessing) jar:file:/C:/Users/Braayy/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.4.7-universal.jar!/cofh/api/CoFHAPIProps.class).
                    Ender IO needs at least 1.4.0 and will NOT work with older versions.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Braayy/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.4.7-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Braayy/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.4.7-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Braayy/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.4.7-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Braayy/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.4.7-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Braayy/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.4.7-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Braayy/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.4.7-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Braayy/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.4.7-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Braayy/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.4.7-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Braayy/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.4.7-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.5.136
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Braayy'/33, l='Testes', x=98,21, y=2,00, z=-1322,85]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_D8
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.2
	OpenGlRenderer: GeForce 6150SE nForce 430/integrated/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by skyboy** [comment]
Is this still a problem with builds 217+?

**Comment by skyboy** [comment]
It seems to be a problem with optifine, for which no support is offered.
