### ISSUE TITLE
CRASH:  Game Crashes upon search of @MineFactory in JEI

### ISSUE THREAD

**Issue by AnthonyKane5528X** [skyboy/MineFactoryReloaded#598]
CRASH:  Game Crashes upon search of @MineFactory in JEI
MRF: 2-2.0.12
CofH:  1.10.2-4.1.4.7
JEI:  1.10.2-3.14.7.419
Forge:  12.18.3.2254

Steps to reproduce:
-Load up game.
-Attempt JEI search and start typing @minef (upon pressing the "f" key the game should freeze and crash)
-Even if you look up individual blocks/items JEI does not show/display the crafting recipe for said items.
-If you are in creative mode and attempt to search using the "Tabs" the game will once again crash.

What I expect to happen:
-Be able to search JEI for @Minefactory Reloaded

Here is what curse forge states after crash:
The game crashed whilst rendering ingredient
Error: java.lang.AbstractMethodError

Crash log from Paste Bin:
https://pastebin.com/70KbTCRH

**Comment by skyboy** [comment]
Your pastebin log is not the same as the problem you're reporting. What you're reporting was fixed by 999526704ca756262cfc8e66d8c67da727d8eb5d, however I don't know what the pastebin error is.
