### ISSUE TITLE
[1.10.2] Crash when generating rubber leaves

### ISSUE THREAD

**Issue by Post-opKen** [skyboy/MineFactoryReloaded#599]
I have a crash when generating or trying to load a chunk that contains a rubber tree.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.4.7-universal.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.3-anarchy.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.1.0.13.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 6/16/17 10:03 PM
Description: Tesselating block model

java.lang.AbstractMethodError: powercrystals.minefactoryreloaded.block.BlockRubberLeaves$$Lambda$515/1099026593.func_186720_a(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;I)I
	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:167)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:229)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:107)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:61)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:293)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:167)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:229)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:107)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)

-- Block model being tesselated --
Details:
	Block: minefactoryreloaded:rubberwood_leaves[check_decay=true,decayable=true,fancy=true,variant=normal]
	Block location: World: (-3896,67,-1632), Chunk: (at 8,4,0 in -244,-102; contains blocks -3904,0,-1632 to -3889,255,-1617), Region: (-8,-4; contains chunks -256,-128 to -225,-97, blocks -4096,0,-2048 to -3585,255,-1537)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)

-- Block being tesselated --
Details:
	Block type: ID #1093 (tile.mfr.rubberwood.leaves // powercrystals.minefactoryreloaded.block.BlockRubberLeaves)
	Block data value: 8 / 0x8 / 0b1000
	Block location: World: (-3896,67,-1632), Chunk: (at 8,4,0 in -244,-102; contains blocks -3904,0,-1632 to -3889,255,-1617), Region: (-8,-4; contains chunks -256,-128 to -225,-97, blocks -4096,0,-2048 to -3585,255,-1537)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)

-- Block being tesselated --
Details:
	Block type: ID #1093 (tile.mfr.rubberwood.leaves // powercrystals.minefactoryreloaded.block.BlockRubberLeaves)
	Block data value: 8 / 0x8 / 0b1000
	Block location: World: (-3896,67,-1632), Chunk: (at 8,4,0 in -244,-102; contains blocks -3904,0,-1632 to -3889,255,-1617), Region: (-8,-4; contains chunks -256,-128 to -225,-97, blocks -4096,0,-2048 to -3585,255,-1537)
Stacktrace:
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:61)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['PostopKen'/262, l='MpServer', x=-3750.97, y=77.74, z=-1591.85]]
	Chunk stats: MultiplayerChunkCache: 1018, 1018
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-116,64,256), Chunk: (at 12,4,0 in -8,16; contains blocks -128,0,256 to -113,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1409992 game time, 2048224 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 112 total; [EntityCreeper['Creeper'/12550, l='MpServer', x=-3704.50, y=15.00, z=-1550.50], EntityPlayerSP['PostopKen'/262, l='MpServer', x=-3750.97, y=77.74, z=-1591.85], EntityLatchedRenderer['unknown'/268, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unknown'/269, l='MpServer', x=-3591.50, y=73.00, z=-1124.50], EntitySpider['Spider'/12047, l='MpServer', x=-3738.50, y=35.00, z=-1507.50], EntityCow['Cow'/10265, l='MpServer', x=-3761.49, y=65.00, z=-1572.58], EntityCow['Cow'/10266, l='MpServer', x=-3770.50, y=66.00, z=-1571.50], EntityCow['Cow'/10267, l='MpServer', x=-3772.55, y=66.00, z=-1571.27], EntityCow['Cow'/10268, l='MpServer', x=-3768.50, y=66.00, z=-1571.50], EntityCow['Cow'/10269, l='MpServer', x=-3770.50, y=66.00, z=-1571.50], EntityCow['Cow'/10270, l='MpServer', x=-3748.40, y=64.00, z=-1573.09], EntityMinecartChest['Minecart with Chest'/11038, l='MpServer', x=-3700.50, y=20.06, z=-1628.50], EntitySkeleton['Skeleton'/13086, l='MpServer', x=-3702.50, y=19.00, z=-1640.50], EntityCow['Cow'/10271, l='MpServer', x=-3749.50, y=64.00, z=-1575.50], EntityChicken['Chicken'/11039, l='MpServer', x=-3701.50, y=63.00, z=-1624.50], EntityCreeper['Creeper'/13087, l='MpServer', x=-3700.50, y=19.00, z=-1637.50], EntityCow['Cow'/10272, l='MpServer', x=-3746.50, y=64.00, z=-1575.50], EntityCreeper['Creeper'/13088, l='MpServer', x=-3787.50, y=29.00, z=-1526.50], EntityChicken['Chicken'/11040, l='MpServer', x=-3697.50, y=63.00, z=-1628.50], EntityCow['Cow'/10273, l='MpServer', x=-3746.50, y=64.00, z=-1573.50], EntityCreeper['Creeper'/13089, l='MpServer', x=-3785.50, y=29.00, z=-1525.50], EntityChicken['Chicken'/11041, l='MpServer', x=-3696.50, y=63.00, z=-1626.50], EntityCow['Cow'/10274, l='MpServer', x=-3755.50, y=64.00, z=-1575.50], EntityCow['Cow'/10275, l='MpServer', x=-3757.50, y=65.00, z=-1575.50], EntityCow['Cow'/10276, l='MpServer', x=-3759.45, y=65.00, z=-1573.36], EntitySheep['Sheep'/10277, l='MpServer', x=-3818.60, y=65.00, z=-1577.45], EntityZombie['Zombie'/13094, l='MpServer', x=-3782.50, y=31.00, z=-1506.50], EntitySheep['Sheep'/10278, l='MpServer', x=-3816.50, y=64.00, z=-1577.50], EntityZombie['Zombie'/13095, l='MpServer', x=-3783.50, y=31.00, z=-1508.50], EntitySheep['Sheep'/10279, l='MpServer', x=-3819.50, y=66.00, z=-1576.50], EntitySheep['Sheep'/10280, l='MpServer', x=-3821.50, y=66.00, z=-1578.50], EntityChicken['Chicken'/10281, l='MpServer', x=-3751.95, y=65.00, z=-1588.32], EntityChicken['Chicken'/10282, l='MpServer', x=-3752.50, y=65.00, z=-1586.50], EntitySkeleton['Skeleton'/13354, l='MpServer', x=-3667.50, y=39.00, z=-1527.50], EntityChicken['Chicken'/10283, l='MpServer', x=-3754.50, y=65.00, z=-1586.50], EntityChicken['Chicken'/10284, l='MpServer', x=-3756.23, y=65.00, z=-1586.20], EntityCreeper['Creeper'/13100, l='MpServer', x=-3724.50, y=42.00, z=-1520.50], EntityCreeper['Creeper'/13120, l='MpServer', x=-3676.50, y=16.00, z=-1506.50], EntityCow['Cow'/10821, l='MpServer', x=-3750.40, y=63.00, z=-1606.58], EntityCow['Cow'/10822, l='MpServer', x=-3753.50, y=64.00, z=-1598.76], EntityCow['Cow'/10823, l='MpServer', x=-3751.48, y=63.00, z=-1607.93], EntityCow['Cow'/10824, l='MpServer', x=-3751.50, y=69.00, z=-1603.50], EntityBat['Bat'/12873, l='MpServer', x=-3683.75, y=58.14, z=-1520.25], EntityBat['Bat'/12874, l='MpServer', x=-3684.30, y=58.52, z=-1524.71], EntityCow['Cow'/10832, l='MpServer', x=-3761.50, y=63.00, z=-1603.50], EntityCow['Cow'/10833, l='MpServer', x=-3763.50, y=63.00, z=-1606.50], EntityCow['Cow'/10834, l='MpServer', x=-3766.50, y=63.00, z=-1606.50], EntityCow['Cow'/10835, l='MpServer', x=-3767.50, y=63.00, z=-1605.50], EntityZombie['Zombie'/11617, l='MpServer', x=-3709.50, y=34.00, z=-1508.50], EntitySpider['Spider'/11875, l='MpServer', x=-3668.50, y=38.00, z=-1539.50], EntityCreeper['Creeper'/13414, l='MpServer', x=-3742.50, y=38.00, z=-1533.50], EntityCreeper['Creeper'/13415, l='MpServer', x=-3743.50, y=38.00, z=-1535.50], EntityCreeper['Creeper'/13416, l='MpServer', x=-3744.50, y=38.00, z=-1536.50], EntitySheep['Sheep'/11368, l='MpServer', x=-3817.51, y=67.00, z=-1664.79], EntitySkeleton['Skeleton'/13417, l='MpServer', x=-3746.50, y=38.00, z=-1534.50], EntityBat['Bat'/12650, l='MpServer', x=-3671.25, y=45.03, z=-1545.50], EntityCyberZombie['Zombie'/12922, l='MpServer', x=-3766.83, y=35.00, z=-1517.30], EntityCyberZombie['Zombie'/12923, l='MpServer', x=-3768.22, y=35.00, z=-1517.78], EntityCyberZombie['Zombie'/12924, l='MpServer', x=-3767.50, y=35.00, z=-1519.50], EntityCreeper['Creeper'/12925, l='MpServer', x=-3767.47, y=35.00, z=-1517.38], EntitySkeleton['Skeleton'/12673, l='MpServer', x=-3693.50, y=41.00, z=-1524.50], EntityMinecartChest['Minecart with Chest'/11141, l='MpServer', x=-3686.50, y=16.06, z=-1638.50], EntityZombie['Zombie'/13445, l='MpServer', x=-3746.50, y=35.00, z=-1526.50], EntityZombie['Zombie'/13446, l='MpServer', x=-3754.50, y=35.00, z=-1522.50], EntityZombie['Zombie'/13448, l='MpServer', x=-3736.50, y=35.00, z=-1505.50], EntityChicken['Chicken'/11145, l='MpServer', x=-3817.90, y=64.00, z=-1638.99], EntityChicken['Chicken'/11146, l='MpServer', x=-3819.09, y=64.00, z=-1640.01], EntityChicken['Chicken'/11147, l='MpServer', x=-3818.41, y=64.00, z=-1639.42], EntityZombie['Zombie'/13452, l='MpServer', x=-3739.50, y=35.00, z=-1505.50], EntityChicken['Chicken'/11148, l='MpServer', x=-3818.50, y=64.00, z=-1636.50], EntityChicken['Chicken'/11149, l='MpServer', x=-3763.50, y=64.00, z=-1641.50], EntityChicken['Chicken'/11150, l='MpServer', x=-3762.50, y=64.00, z=-1642.50], EntityChicken['Chicken'/11151, l='MpServer', x=-3765.56, y=64.83, z=-1640.51], EntityChicken['Chicken'/11152, l='MpServer', x=-3767.50, y=66.00, z=-1644.50], EntityMinecartChest['Minecart with Chest'/11153, l='MpServer', x=-3728.50, y=18.06, z=-1643.50], EntityCreeper['Creeper'/13202, l='MpServer', x=-3686.50, y=41.00, z=-1530.50], EntityCyberZombie['Zombie'/12436, l='MpServer', x=-3698.50, y=34.00, z=-1508.50], EntityPig['Pig'/9622, l='MpServer', x=-3717.28, y=66.00, z=-1519.37], EntityCreeper['Creeper'/12182, l='MpServer', x=-3668.50, y=29.00, z=-1550.50], EntityPig['Pig'/9623, l='MpServer', x=-3707.53, y=65.00, z=-1519.26], EntityCreeper['Creeper'/12183, l='MpServer', x=-3671.50, y=29.00, z=-1547.50], EntityZombie['Zombie'/12184, l='MpServer', x=-3674.50, y=29.00, z=-1550.50], EntityZombie['Zombie'/12185, l='MpServer', x=-3675.50, y=29.00, z=-1548.50], EntityCyberZombie['Zombie'/11674, l='MpServer', x=-3683.50, y=45.00, z=-1545.50], EntityPig['Pig'/9883, l='MpServer', x=-3666.50, y=64.00, z=-1536.50], EntityPig['Pig'/9884, l='MpServer', x=-3668.50, y=66.00, z=-1536.34], EntityMinecartChest['Minecart with Chest'/9885, l='MpServer', x=-3754.50, y=34.06, z=-1549.50], EntityMinecartChest['Minecart with Chest'/9886, l='MpServer', x=-3730.50, y=37.06, z=-1542.50], EntityBat['Bat'/12198, l='MpServer', x=-3743.93, y=38.64, z=-1533.83], EntitySkeleton['Skeleton'/12457, l='MpServer', x=-3767.50, y=19.00, z=-1509.50], EntityCreeper['Creeper'/12971, l='MpServer', x=-3680.50, y=12.00, z=-1616.70], EntitySkeleton['Skeleton'/12980, l='MpServer', x=-3691.50, y=33.00, z=-1518.50], EntityZombie['Zombie'/12735, l='MpServer', x=-3740.50, y=33.00, z=-1515.50], EntitySkeleton['Skeleton'/13503, l='MpServer', x=-3666.50, y=25.00, z=-1539.50], EntityZombie['Zombie'/12736, l='MpServer', x=-3740.50, y=33.00, z=-1514.50], EntityZombie['Zombie'/13008, l='MpServer', x=-3736.50, y=32.00, z=-1530.50], EntityCreeper['Creeper'/12757, l='MpServer', x=-3781.50, y=35.00, z=-1545.50], EntityMinecartChest['Minecart with Chest'/11221, l='MpServer', x=-3720.50, y=22.06, z=-1659.50], EntityCreeper['Creeper'/12758, l='MpServer', x=-3783.50, y=35.00, z=-1549.50], EntityPig['Pig'/11222, l='MpServer', x=-3724.50, y=70.00, z=-1657.50], EntityPig['Pig'/11223, l='MpServer', x=-3724.50, y=71.00, z=-1663.50], EntityPig['Pig'/9691, l='MpServer', x=-3710.07, y=65.00, z=-1520.17], EntityBat['Bat'/11740, l='MpServer', x=-3692.82, y=41.00, z=-1526.51], EntityPig['Pig'/9692, l='MpServer', x=-3708.48, y=65.00, z=-1520.26], EntityMinecartChest['Minecart with Chest'/9693, l='MpServer', x=-3731.50, y=34.06, z=-1534.50], EntitySheep['Sheep'/11230, l='MpServer', x=-3823.50, y=66.00, z=-1662.50], EntityMinecartChest['Minecart with Chest'/11231, l='MpServer', x=-3786.50, y=31.06, z=-1652.50], EntityPig['Pig'/11232, l='MpServer', x=-3730.55, y=71.00, z=-1658.95], EntityLatchedRenderer['unknown'/12773, l='MpServer', x=-3750.97, y=77.74, z=-1591.85], EntityCreeper['Creeper'/13555, l='MpServer', x=-3698.50, y=21.00, z=-1647.50], EntityZombie['Zombie'/13045, l='MpServer', x=-3742.50, y=28.00, z=-1561.50], EntityZombie['Zombie'/13310, l='MpServer', x=-3773.50, y=35.00, z=-1651.50]]
	Retry entities: 2 total; [EntityLatchedRenderer['unknown'/268, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unknown'/269, l='MpServer', x=-3591.50, y=73.00, z=-1124.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:57)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1312891648 bytes (1252 MB) / 2345664512 bytes (2237 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 98
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 Optifine OptiFine_1.10.2_HD_U_D8 70 mods loaded, 70 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316.jar) 
	UCHIJAAAA	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	UCHIJAAAA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.10.2-1.1.6.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UCHIJAAAA	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf-1.10.2-1.4.4.347.jar) 
	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJAAAA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.11.25} [Chisel] (Chisel-MC1.10.2-0.0.11.25.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.9.267} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJAAAA	cofhcore{4.1.4} [CoFH Core] (CoFHCore-1.10.2-4.1.4.7-universal.jar) 
	UCHIJAAAA	extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.16.jar) 
	UCHIJAAAA	coroutil{1.10.2-1.1.16} [CoroUtil Library] (coroutil-1.10.2-1.1.16.jar) 
	UCHIJAAAA	configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.16.jar) 
	UCHIJAAAA	ctm{MC1.10.2-0.1.0.13} [CTM] (CTM-MC1.10.2-0.1.0.13.jar) 
	UCHIJAAAA	cyberware{beta-0.2.10} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.10.jar) 
	UCHIJAAAA	darkutils{1.1.8.finalrc2} [Dark Utilities] (DarkUtilities-1.1.8.finalrc2.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCHIJAAAA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	FlatBedrockx{1.2.1} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.2.1_1.9.4.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.3-anarchy.jar) 
	UCHIJAAAA	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHIJAAAA	ichunutil{6.3.2} [iChunUtil] (iChunUtil-1.10.2-6.3.2.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.27} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.27.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.7} [JourneyMap] (journeymap-1.10.2-5.4.7.jar) 
	UCHIJAAAA	levels{3.0.2} [Levels 3] (Levels 3-1.10.2-3.0.2-beta.jar) 
	UCHIJAAAA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCHIJAAAA	boots{1.0} [Long Fall Boots] (LongFallBoots - Hard Mode.jar) 
	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJAAAA	minefactoryreloaded{2.9.0B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.10.2]2.9.0B1-216.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{2.9.0B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.10.2]2.9.0B1-216.jar) 
	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.10.2-1.13.jar) 
	UCHIJAAAA	mobdismemberment{6.0.0} [MobDismemberment] (MobDismemberment-1.10.2-6.0.0.jar) 
	UCHIJAAAA	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.10.2).jar) 
	UCHIJAAAA	openglider{@VERSION@} [Open Glider] (OpenGlider-1.10.2-0.2.3.jar) 
	UCHIJAAAA	reborncore{2.13.6.142} [RebornCore] (RebornCore-1.10.2-2.13.6.142-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.6.142} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.13.6.142-universal.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.7.9} [Storage Drawers] (StorageDrawers-1.10.2-3.7.9.jar) 
	UCHIJAAAA	refinedstorage{1.2.26} [Refined Storage] (refinedstorage-1.2.26.jar) 
	UCHIJAAAA	rebornstorage{1.0.0} [RebornStorage] (RebornStorage-1.10.2-1.0.3.30.jar) 
	UCHIJAAAA	thermalfoundation{2.1.1} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.1.3-universal.jar) 
	UCHIJAAAA	redstonearsenal{2.0.4} [Redstone Arsenal] (RedstoneArsenal-1.10.2-2.0.4.33-universal.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.664} [Reliquary] (Reliquary-1.10.2-1.3.3.664.jar) 
	UCHIJAAAA	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UCHIJAAAA	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
	UCHIJAAAA	soulshardstow{1.10.2-2.6.7-48} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.7-48.jar) 
	UCHIJAAAA	spikemod{1.10.2-1.2.1} [Spike Mod] (spikemod-1.10.2-1.2.1.jar) 
	UCHIJAAAA	stg{1.0.2} [SwingThroughGrass] (stg-1.0.2.jar) 
	UCHIJAAAA	theoneprobe{1.4.7} [The One Probe] (theoneprobe-1.1x-1.4.7.jar) 
	UCHIJAAAA	thermalexpansion{5.1.3} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.3.4-universal.jar) 
	UCHIJAAAA	thermaldynamics{2.0.4} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.4.6-universal.jar) 
	UCHIJAAAA	tombmanygraves{1.10.2-2.1.16} [Tomb Many Graves] (TombManyGraves-1.10.2-2.1.16.jar) 
	UCHIJAAAA	torchmaster{1.4.0.32} [TorchMaster] (torchmaster_1.10.2-1.4.0.32.jar) 
	UCHIJAAAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.10.2-1.1.2.jar) 
	UCHIJAAAA	waystones{2.0.12} [Waystones] (Waystones_1.10.2-2.0.12.jar) 
	UCHIJAAAA	weaponcaseloot{4.0.3} [WeaponCaseLoot] (weaponcaseloot-1.10.2-4.0.3.jar) 
	UCHIJAAAA	zombieawareness{1.10.2-1.11.7} [Zombie Awareness] (zombieawareness-1.10.2-1.11.7.jar) 
	UCHIJAAAA	denseores{1.0} [denseores] (denseores-1.11-1.0.2.jar) 
	Loaded coremods (and transformers): 
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.4.7-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.3-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
CTMCorePlugin (CTM-MC1.10.2-0.1.0.13.jar)
  team.chisel.ctm.client.asm.CTMTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	minefactoryreloaded: -[1.10.2]2.9.0B1-216
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderStorage Invalid Fingerprint Reports: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.6.142
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 1
	Launched Version: forge-12.18.3.2316
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8320 Eight-Core Processor 
	OptiFine Version: OptiFine_1.10.2_HD_U_D8
	Render Distance Chunks: 16
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13469 Compatibility Profile Context 21.19.519.2
	OpenGlRenderer: AMD Radeon HD 7800 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by skyboy** [comment]
Fixed by 999526704ca756262cfc8e66d8c67da727d8eb5d
