### ISSUE TITLE
[1.10.2] Farmer not planting mods seeds

### ISSUE THREAD

**Issue by NerdCraft** [skyboy/MineFactoryReloaded#601]
![2017-06-17_12 56 45](https://user-images.githubusercontent.com/13489837/27254335-bd8aab96-535c-11e7-8c3d-6c4c706e2347.png)

**Comment by skyboy** [comment]
It has no idea what they are, so this is normal.

It will take some time before mods support MFR and MFR supports mods again.

**Comment by zackeezy** [comment]
Just to add to this, it also doesn't support Agricraft.

**Comment by BlakeBr0** [comment]
@NerdCraft I whipped up a quick compat addon for Mystical Agriculure/Additions https://minecraft.curseforge.com/projects/mystical-agriculture-mfr-compat
