### ISSUE TITLE
[1.10.2] Thermal Expansions recipes not working.

### ISSUE THREAD

**Issue by MUSE-iC** [skyboy/MineFactoryReloaded#604]
Ive set the config on the server to true for thermal expansion recipes on my server but they dont show up on JEI.

I tried them anyways in case they were working but just not showing up JEI. That also didnt work.
I tested it in just a single player world and I also tried disabling/enabling the Ender IO recipes.

**Comment by P3pp3rF1y** [comment]
At the moment there is almost no mod integration included, which means there are no TE recipes either.

**Comment by Miner94** [comment]
there are no recipes for some of the machines

**Comment by DeadSix27** [comment]
@P3pp3rF1y that includes support for Natura saplings in planter not working?

**Comment by P3pp3rF1y** [comment]
I haven't tested those and actually don't even see any support for them that would have been there previously so if I they did work in 1.7.10 then it's likely something has changed on Natura side when this was ported to 1.10.  We will be going through the integrations and can look into this one as well when there's time.

**Comment by AnthonyKane5528X** [comment]
@P3pp3rF1y 
Do you know if the CofH recipes for MFR machines will be fixed in the next release?
-Not that I mind the vanillia recipes (even though they are dirt cheap).  I just prefer the CofH recipes.  It just feels a bit more, fair and balanced (IMO).

**Comment by DeadSix27** [comment]
@AnthonyKane5528X If they do not, I recommend just setting the recipes with minetweaker and minetweaker recipe maker, quick and easy.

**Comment by lightningmanmftw** [comment]
I've written a [minetweaker script](https://pastebin.com/kThL0yJN) that removes vanilla recipes and adds Themal Expansion recipes. I have my config set to vanilla so that I didn't have to put in ones like sheet plastic. It should display both recipes if your config is set to Ender IO but it will not display simple recipes like sheet plastic if set to Thermal Expansion.
