### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by piedpipr314** [skyboy/MineFactoryReloaded#606]
While trying to narrow down a problem trying out the new MFR, I only loaded three mods in a simple pack.  I got this crash. Looks to me like it's trying to init the MFR fluids and fails, could be wrong. 

https://pastebin.com/keZ3Kjs6

**Comment by MasterGeneral156** [comment]
Literally came here to post the same crash. :D Can confirm this is happening on 2.9.0B1-221

**Comment by Miner94** [comment]
yea trying to place some of the machines also crashes the game

**Comment by Miner94** [comment]
well actually it doesnt crash it freezes

**Comment by skyboy** [comment]
Well, 4.1.6 of core was supposed to include a commit I had made about an hour before it was released, but apparently it did not. Wait for 4.1.7 I guess.
