### ISSUE TITLE
Thermal Dynamics incompatability

### ISSUE THREAD

**Issue by NicosaurusRex99** [skyboy/MineFactoryReloaded#609]
i connected a fluiduct to the slaughter house and grinder and this is the crash i got

https://pastebin.com/jMELACUg

**Comment by P3pp3rF1y** [comment]
This actually doesn't have anything to do with Thermal Dynamics. It's the same issue as #608 will be resolved with the next release of cofhcore.

**Comment by NicosaurusRex99** [comment]
Cool thanks!
