### ISSUE TITLE
[1.10.2] Modpack crashes on start with MFR

### ISSUE THREAD

**Issue by Curunir** [skyboy/MineFactoryReloaded#611]
I have tried including the new MFR build into my private 1.10.2 modpack, but the pack always runs into the same crash on startup, something about ModelBakery, and I think buckets were mentioned. As others apparently can get the mod to work, any chance you can tell me where to look for the error? Clearly something in my pack is clashing with MFR. Crash log attached, obtained with the latest version, 2.9.0B1-221.

[crash-2017-06-21_23.33.03-client.txt](https://github.com/skyboy/MineFactoryReloaded/files/1092990/crash-2017-06-21_23.33.03-client.txt)

**Comment by CitiesXL2815** [comment]
This issue is Duped, before reporting see if any issue are the same before reporting

**Comment by Curunir** [comment]
I checked for open issues about this and found none. It says in the closed ticket that it is resolved, so in which build is it expected to work? Or do I have to update/change a different mod?

**Comment by P3pp3rF1y** [comment]
We needed a change in core for the fix to work. But now that it is out you shoudl be able to run it with the latest versions of both MFR and Cofh Core - MineFactoryReloaded-[1.10.2]2.9.0B1-221 and CoFHCore-1.10.2-4.1.7.11-universal.

**Comment by Curunir** [comment]
I just tried with these versions, and it still crashes just like before. Crash log attached.
[crash-2017-06-23_19.13.26-client.txt](https://github.com/skyboy/MineFactoryReloaded/files/1098529/crash-2017-06-23_19.13.26-client.txt)

**Comment by skyboy** [comment]
I don't know what's causing this or why who is affected by it flip-flops based on what method of overriding the vanilla bucket is used, but I'm considering marking this as `wontfix` since it's being caused, sporadically, by another mod.

If you can identify which mod is actually causing the issue, it would help tremendously in resolving it.

**Comment by balcas** [comment]
I compared my modpack with Curunirs list. And started removing mods one by one and adding them back.
After removal of OpenComputers it started up.

**Comment by balcas** [comment]
Let me correct myself it was Open Computers Refined Storage Driver. I added OpenComputers back and it worked but i had an addon to it OCRSDriver and then i readded it and it broke again. And we both had it with Curunir.

**Comment by Curunir** [comment]
I tried taking these out of my pack to check, but it still crashes with all these removed (some for dependencies):
Open Computers Refined Storage Driver
Open Computers
Refined Storage
Reborn Storage
Wireless Crafting Grid

Also still only the client crashing. The server starts up fine.

**Comment by balcas** [comment]
Weird well my server is running perfectly fine and it seems the modpack is running for everyone. Check my modlist and try checking the mods that is not in my modpack then :) Check what helps and write here that skyboy would know what is conflicting. I will PM you my modlist

**Comment by balcas** [comment]
One of the guys from the server client was not loading even we all were playing. So OpenComputers removal solved it for some of us but for one guy client didnt load doesnt matter what he was doing.

**Comment by balcas** [comment]
yesturday we removed all the mods in common with Curunir and it was still crashing for the player from my server.

**Comment by Tomstah** [comment]
Hi, associate of Curunir's here.  Just a quick thing I pointed out; I asked for his forge log and there were quite a bit of relations to the error to CodeChickenLIB.  10 seconds before the crash, this was posted:

`[23:04:39] [Client thread/INFO] [STDERR/]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]:     at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:170)`

Then, when we look in the error, we find:

```
java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177596_a(ModelBakery.java:441)
```

I'll be the first one to admit I'm not a coder, but the first line of an error?   Not to mention it's the only thing I could find referenced in the error.   Another suggestion if it doesn't pass the test is to keep checking for references in the errors and knock off the mods one by one until it fixes itself or until the problems is either it's raw self, or a problem with Minecraft/Forge (Which from the information I've seen, it isn't).  I'd be happy to continue to contribute, including finding references if needed.

**Comment by balcas** [comment]
Yeah that was my plan also. But what happen after removal of OpenComputers it fixed for me. But not for a guy from my server. So i guess ill have to use him to figure it out. :)

**Comment by Staegrin** [comment]
" # If true, replaces the vanilla milk bucket so milk can be placed in the world.
        B:MilkBucket=false"
Changing this setting to false seems to help. 

Though the startup log still contains the 
	net.minecraftforge.fml.common.eventhandler.ASMEventHandler_306_TextureMetadataHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
	
error 4 times.

**Comment by skyboy** [comment]
Yeah, turning the milk bucket feature off will remove the crashes, but doesn't solve the problem. I honestly don't know what's going on here, and seems it could be a problem with forge.

**Comment by smudgerox** [comment]
i'm wondering if it's an interaction with biomesoplenty- anyone else using it? i'm dealing with the same issue here. the potentially offending line is:

"texture settings" {
    # Override the Forge bucket texture and use ours instead (It's nicer!) [default: true]
    B:"Enable Biomes O' Plenty Bucket Textures"=true

it's in config/biomesoplenty/misc.cfg, line 9-11.

i'll test it out and report back.

**Comment by accessdenied0** [comment]
I do not use Biomesoplenty, and it crashes by me, too.

Funny enough: The potential Fix from #600 is now broken again with the same issue.
This is really strange... I can't loose the feeling it could be Forestry or something... I might do a 1 by 1 mod test... it might take a while.

**Comment by smudgerox** [comment]
seems like that's not the problem either, process of elimination though i guess.

**Comment by Tomstah** [comment]
Here if you guys have any log files send 'em my way.  I'll see if I can get some references.

**Comment by Curunir** [comment]
I cannot be Forestry, as that is not in my (affected) pack. I rather suspect that a number of mods are using some bucket-rendering related function that clashes with something MFR is doing. I would investigate this further, but I am not a coder, just a lowly support monkey, and that is as far as my understanding goes. Please tell me if you need any tests run, I will gladly contribute however I can. Having MFR back is worth some trouble.

**Comment by P3pp3rF1y** [comment]
Would you be able to share full log (latest.log from logs folder) from when it crashed? Some people mentioned seeing warning messages even before crash. That may help us understand better what it is doing. 

And the issue based on what I can see isn't just purely rendering. It does happen in rendering code but at the moment that it tries to pull milk bucket data from item registry and can't find it there for some reason.

**Comment by NogueiraMaier** [comment]
I had this mistake also in the milk bucket.
I updated the forge and left the config folder
solved the problem
Now I have a problem with a single machine in MFR, BlockSmasher
and drop and error,
[crash-2017-10-06_16.57.28-client.txt](https://github.com/skyboy/MineFactoryReloaded/files/1364112/crash-2017-10-06_16.57.28-client.txt)
