### ISSUE TITLE
Some EnderIO recipes don't work

### ISSUE THREAD

**Issue by bogger33** [skyboy/MineFactoryReloaded#612]
harvester
block breaker
grinder
slaughterhouse
meat packer
fruit picker
chunk loader

haven't messed with the config at all, can't even find the config file in fact

**Comment by AnthonyKane5528X** [comment]
@bogger
-I noticed this as well.  You may need to go into the config files and change it so that it uses MFR/Vanilla recipes only.  If you set it to use EnderIO recipes some machines have none.  And as far as I could tell the Thermal Expansion recipes are not working at all.

**Comment by bogger33** [comment]
what's the config file called? I couldn't find it

**Comment by AnthonyKane5528X** [comment]
The Config file is under "Powercrystals"

**Comment by skyboy** [comment]
Fixed by f8c6f88de04114fed7c5e0e1dc8a5aa381995e2c
