### ISSUE TITLE
[1.10.2] Grinder crashes server

### ISSUE THREAD

**Issue by DeadSix27** [skyboy/MineFactoryReloaded#614]
After placing the grinder the server reports a lot of errors and eventually crashes:

Stacktrace: https://gist.github.com/DeadSix27/01976b3a15bd9837e3ea74f1754653e3 (that error got repeated many times)

**Comment by skyboy** [comment]
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/608
