### ISSUE TITLE
I keep getting this error with every single MFR version that i tried. 1.10.2

### ISSUE THREAD

**Issue by balcas** [skyboy/MineFactoryReloaded#618]
First there were issues to load up the server because i was running spongeforge.
But now minecraft client itself doesnt load.
[crash-2017-06-24_18.54.41-client.txt](https://github.com/skyboy/MineFactoryReloaded/files/1099963/crash-2017-06-24_18.54.41-client.txt)

**Comment by CitiesXL2815** [comment]
this already reported #600
