### ISSUE TITLE
Issue with item names in modpack :'(

### ISSUE THREAD

**Issue by 1ChaVnere** [skyboy/MineFactoryReloaded#619]
As the title says, I'm the victim of a nasty bug in my pack. I'm not a hundred percent sure it's from MFR but it's the only mod whith which I've this issue, in fact the game charges well everything works fine but (cuz there is always one ><', all mfr's items have "bugged" names so instead of having for example a Mining Laser item I've the item as it is called IN the mod itself : item.mfr.miningLaser... or something like this. (I'll link a picture which shows the item's name). I just checked if the bug was happening when playing mfr outside a modpack and names worked well so maybe it's an incompatibility or a strange interaction between the mods. Btw you will find all the mods I play with will be in the latest file bellow :)

Here is the logs when launching the game and then when launching the map : 
[latest.txt](https://github.com/skyboy/MineFactoryReloaded/files/1100032/latest.txt)
Btw in this log I "crashed" the game by myself at the end cuz I placed one of the uncraftable blocks and it completly froze, and I had to uninstall and reinstall the mod to delete the "glitched" block from the map and make it playable again (I won't try to make the bug happen gain even with other uncraftable machine). Sorry I don't remember which block caused this but I think you can find it in the logs but I imagine that this bug may be normal because the item is uncraftable.

Here is the picture of the weird names : 
![sans titre](https://user-images.githubusercontent.com/24493900/27512420-654b2e40-593f-11e7-88e0-066f7cce939e.png)

Finally here is a mod list : 
[modlist.txt](https://github.com/skyboy/MineFactoryReloaded/files/1100038/modlist.txt)

**Comment by 1ChaVnere** [comment]
After looking the log and searching for the keyword "name" I've found lines like this one idk if ot is related _"[00:05:32] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 8 column 6."_



For the keyword mfr I've found some broken recipes xD (lines 5773/5713/5653/5470/5590  and much more :/ with notepad++) and moreover i've foud this suspect line _"[00:04:54] [Client thread/INFO]: Skipping interface powercrystals.minefactoryreloaded.api.IMFRHammer from missing mod MineFactoryReloaded."_



Finally I guess these lines are the error for the lagging block : 

_[00:13:44] [Netty Server IO #1/ERROR]: There was a critical exception handling a packet on channel Waila java.lang.VerifyError: Bad access to protected data in invokevirtual Exception Details: Location: cofh/asmhooks/world/WorldServerProxy.func_72970_h()Lnet/minecraft/world/chunk/IChunkProvider; @4: invokevirtual Reason: Type 'net/minecraft/world/WorldServer' (current frame, stack[0]) is not assignable to 'cofh/asmhooks/world/WorldServerProxy' Current Frame: bci: @4 flags: { } locals: { 'cofh/asmhooks/world/WorldServerProxy' } stack: { 'net/minecraft/world/WorldServer' } Bytecode: 0x0000000: 2ab4 003a b603 beb0 at powercrystals.minefactoryreloaded.tile.machine.TileEntityGrinder.func_145834_a(TileEntityGrinder.java:80) ~[TileEntityGrinder.class:?] at powercrystals.minefactoryreloaded.tile.machine.TileEntitySlaughterhouse.func_145834_a(TileEntitySlaughterhouse.java:31) ~[TileEntitySlaughterhouse.class:?] at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:809) ~[asv.class:?] at net.minecraft.world.World.func_175690_a(World.java:2461) ~[aid.class:?] at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785) ~[asv.class:?] at net.minecraft.world.World.func_175625_s(World.java:2402) ~[aid.class:?] at mcp.mobius.waila.network.Message0x01TERequest.channelRead0(Message0x01TERequest.java:100) ~[Message0x01TERequest.class:?] at mcp.mobius.waila.network.Message0x01TERequest.channelRead0(Message0x01TERequest.java:28) ~[Message0x01TERequest.class:?] at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) ~[netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) ~[netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) ~[netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) ~[netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) ~[netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[netty-all-4.0.23.Final.jar:4.0.23.Final] at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:100) [FMLProxyPacket.class:?] at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149) [eo.class:?] at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51) [eo.class:?] at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-all-4.0.23.Final.jar:4.0.23.Final] at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleServerSideCustomPacket(NetworkDispatcher.java:446) [NetworkDispatcher.class:?] at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:269) [NetworkDispatcher.class:?] at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:73) [NetworkDispatcher.class:?] at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.local.LocalChannel.finishPeerRead(LocalChannel.java:326) [netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:45) [netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:312) [netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-all-4.0.23.Final.jar:4.0.23.Final] at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.23.Final.jar:4.0.23.Final] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]..._

**Comment by skyboy** [comment]
Resolved by 12b354d92667cd06893d464fc13807b5b9bc29f8 and 0545f6911ff0944e2c8e403a9c35ecbfa1efde14

**Comment by 1ChaVnere** [comment]
Perfect ! But is the second "lagging block" bug fixed or not ?
