### ISSUE TITLE
Issue:  Mob Essense not working with Thermal Expansion

### ISSUE THREAD

**Issue by AnthonyKane5528X** [skyboy/MineFactoryReloaded#620]
CofHcore: 1.10.2-4.1.7.11
Thermal Expansion: 1.10.2-5.1.6.8
Minefactory Reloaded: [1.10.2]2.9.0B1-220

Issue:
-Attempted to pipe "Mob Essense" into a Thermal Expansion Reactant Dynamo.
-Mob Essence FAILS to pipe into dynamo.  The block will not accept it.
-Went into the CofH configs for Thermal Expansion.  

Tried all the following:
* mobessence
* mob_essence
* essence

Nothing worked to get Thermal Expansions Reactant Dynamo to take Mob Essense fluid.

Please also note:  Fluid itself registers as Mob Essence in JEI.  Under the "Forge Bucket" it shows as "Essence".  The Metadata name is mob_essence.  Also if you are in creative mode and place down a bucket of "mob essence" and try to pick up the source block with an empty bucket, the block will be picked up, but you will only get an empty bucket.

Not entirely sure where the disconnect is and why the fluid is not working with Thermal Expansion or being gatherable with a bucket.

**Comment by skyboy** [comment]
This is an issue for Thermal Expansion ([report here](https://github.com/CoFH/Feedback/issues)), and I've opened a new issue for the bucket error
