### ISSUE TITLE
Mob essence cannot be picked up by buckets

### ISSUE THREAD

**Issue by skyboy** [skyboy/MineFactoryReloaded#621]
As mentioned in https://github.com/skyboy/MineFactoryReloaded/issues/620#issue-238348727

**Comment by AnthonyKane5528X** [comment]
Just a heads up.  I asked on the discord server, and some said that this is "intended" functionality,  If you're in "creative" mode and pick up a fluid source block with an empty bucket, you will get an empty bucket.  

So if this makes sense then close the ticket as they said this is how its suppose to work.
