### ISSUE TITLE
[1.10.2] MFR and LiteLoader (NullPointerException)

### ISSUE THREAD

**Issue by Bassadx** [skyboy/MineFactoryReloaded#622]
Hey,

so I'm currently trying to get a decent mod collection working for 1.10.2 (only played 1.7 so far and decided to step it up). Both, LiteLoader and MFR, are important to me and I want to include them, but it appears that in 1.10.2 they dont work really well together.

Here's the crash log and the full error message: 
https://pastebin.com/LSYsakQK

"The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game"

I tested it with only MFR(version 2.9.0B1-222) and LiteLoader (latest 1.10.2 version). I can use one or the other alone in my personal modpack, but not both together, thats why I figured I post it here (and will do so on the LiteLoader site).

Nothing more I can really say, since my Java knowledge is reeeeeally basic :P

**Comment by joshricker** [comment]
Can confirm this issue, getting the very same thing.

**Comment by Curunir** [comment]
This is the same issue I reported. I just checked by removing LiteLoader and all of its mods, and the crash still happens here. Probably something else, or several things that can trigger this bug.
https://github.com/skyboy/MineFactoryReloaded/issues/611
