### ISSUE TITLE
[1.10.2] Safari nets cannot be piped out of Auto-Spawner

### ISSUE THREAD

**Issue by Post-opKen** [skyboy/MineFactoryReloaded#624]
Not sure if this is intended or not.

I tried to automate the auto-spawner by piping in and out safari nets using Thermal Dynamics itemducts. Safari nets pipe in just fine, but cannot be automatically removed.

**Comment by skyboy** [comment]
This seems to be a problem with Thermal Dynamics, as MFR does not prohibit extraction from the AutoSpawner.

**Comment by skyboy** [comment]
This is now solved in MFR, and was confirmed as an inconsistency with Thermal Dynamics
