### ISSUE TITLE
Issues with Industrial Craft 2 Localization

### ISSUE THREAD

**Issue by SpaceRiceBowl** [skyboy/MineFactoryReloaded#633]
I've had issues with the text for IC2 Items displaying incorrectly, and I've narrowed it down to this mod causing it. 
https://cdn.discordapp.com/attachments/320973463391174656/330848498784403456/2017-07-01_19.13.24.png
https://cdn.discordapp.com/attachments/320973463391174656/330848508737224716/2017-07-01_19.13.26.png

**Comment by skyboy** [comment]
We have no code relating to the language registry, report this to the IC2 tracker.
