### ISSUE TITLE
[1.10.2] Rubber Trees not Farmable 

### ISSUE THREAD

**Issue by maginator** [skyboy/MineFactoryReloaded#634]
Hi there. I try to Farm Rubber Trees with Ender Io´s Farmingstation or from Progresive Automation the Tree Chopper nothing work. And the recipe of the Harvester dosent show in Jei and no its not disable in the Config

Forge : 1.10.2 - 12.18.3.2185
MFR: 2.9.0 B1 220

**Comment by P3pp3rF1y** [comment]
So ender io and progressive automation support for these you need to follow up at their bug trackers. 

And missing recipe I guess is caused by having ender io recipes turned on. The version that you use doesnt have these fixed.
So try to update to latest alpha and confirm if that fixed the issue.

**Comment by maginator** [comment]
Yes it is Fixed in the New Version Thx
