### ISSUE TITLE
Block Smasher Crash

### ISSUE THREAD

**Issue by 1ChaVnere** [skyboy/MineFactoryReloaded#636]
I'm playing on modpack and each time i place a block smasher the game crash and i've to load the map without mfr to erase the block.
[crash-2017-07-02_21.33.09-client.txt](https://github.com/skyboy/MineFactoryReloaded/files/1118032/crash-2017-07-02_21.33.09-client.txt)

**Comment by skyboy** [comment]
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/616#issuecomment-311203224

**Comment by 1ChaVnere** [comment]
BUT THE BUG ISN'T FIXEX WITH THE LAST VERSIONS OF COFHCORE AND MFR

**Comment by 1ChaVnere** [comment]
woops sorry for maj
