### ISSUE TITLE
Recipes won't load with JEI

### ISSUE THREAD

**Issue by fcpwiz** [skyboy/MineFactoryReloaded#637]
I'm using `MineFactoryReloaded-[1.10.2]2.9.0B1-226.jar`, `CoFHCore-1.10.2-4.1.9.13-universal.jar`, and `jei_1.10.2-3.14.7.420.jar`. When searching any MineFactory Reloaded block/item in JEI and clicking on it, no recipe/recipe GUI is displayed.

**Comment by MUSE-iC** [comment]
I just checked and its working fine for me. If those are your only mods make sure that vanilla recipes are set to true in the config file.

**Comment by fcpwiz** [comment]
I can't see any MFR configs. @MUSE-iC

**Comment by MUSE-iC** [comment]
@fcpwiz 
Its inside a folder called powercrystals inside the config folder.
config>powercrystals>minefactoryreloaded>common.cfg

**Comment by fcpwiz** [comment]
@MUSE-iC Is this the part of the config you’re talking about?

```
RecipeSets {
    # If true, MFR will register its EnderIO-based recipes.
    B:EnderIO=true

    # If true, MFR will register its Thermal Expansion-based recipes.
    B:ThermalExpansion=false

    # If true, MFR will register its standard (vanilla-item-only) recipes.
    B:Vanilla=false
}
```

**Comment by P3pp3rF1y** [comment]
It is. Do you have enderio added in the pack? Because you have it set to use EnderIO recipes only. if you want the MFR regular recipes set B:Vanilla=true

**Comment by fcpwiz** [comment]
@P3pp3rF1y Could I set all 3 to true?

**Comment by P3pp3rF1y** [comment]
You could, but thermal expansion recipes are currently not included so that option will do nothing. 

Can you confirm that it fixed your issue and actually that you didn't have enderio included previously and thus no recipes in JEI?

**Comment by fcpwiz** [comment]
I do have EnderIO. I’m using a modpack I created. So what options should I set to true?

**Comment by fcpwiz** [comment]
Also, I can't fully test this due to https://github.com/skyboy/MineFactoryReloaded/issues/625#issuecomment-312893277.

**Comment by P3pp3rF1y** [comment]
Up to you, enderio enables recipes that use enderio components, vanilla enables vanilla MFR recipes. you can have both of those enabled as well.
