### ISSUE TITLE
[1.10.2] Startup Crash with Custom Modpack

### ISSUE THREAD

**Issue by StaticShielding** [skyboy/MineFactoryReloaded#646]
Hello,
I tried to put together a private custom Modpack for myself for MC Version 1.10.2 with forge 12.18.3.2316.
At startup (singleplayer on local machine) the game crashes with the following error log:
[crash-2017-07-05_01.11.53-client.txt](https://github.com/skyboy/MineFactoryReloaded/files/1123198/crash-2017-07-05_01.11.53-client.txt)
Since i couldnt find any mention of a specific mod in the file I have deactivated all mods and reactivated them in smaller batches to narrow the issue down. At the end i found that i could start the pack without problems if only MFR was deactivated. 
It seems to be somewhat related to issue #611 though i have no mention of a bucket in my logs.

I can provide more logs with different mods deactivated if that helps resolve this.
Hope this can be resolved somehow as i would really like to have MFR in my modpack.

**Comment by skyboy** [comment]
This is the same kind of crash as #611, but for a different reason; I suspect that another mod is overriding the vanilla bucket and that's where the incompatibility. You should be able to just disable the milk bucket via config and have it launch: tell me if you can drink the bucket when you do that.

**Comment by StaticShielding** [comment]
Gotta admit i didnt think to try that as my error log didnd contain the bucket anywhere.
If disabled, i can now start the game without apparent problems.
I can also still drink the milk bucket.
Will report back if i get another error while ingame. 
If you need me to do any more tests to fix this in a future build, just let me know.

**Comment by Th3Z0n3** [comment]
I can confirm that bug. And i also can confirm the workaround from StaticShielding. Disable the MilkBucket.

**Comment by piedpipr314** [comment]
If you can get a pack to actually load with the Milk Bucket enabled, it does the crash in https://github.com/skyboy/MineFactoryReloaded/issues/647 and I'll see if I can replicate it.

**Comment by piedpipr314** [comment]
I've written this before, but so you guys know, if I load MFR in a smaller pack with fewer mods, it does NOT crash.  It does, however, show in logs.  If you guys need more info, let me know.

**Comment by piedpipr314** [comment]
Common mods that I have: All COFH, EnderIO, Baubles, Botania, and I've pretty much narrowed it down to either EnderIO or Botania.  I'm pretty sure Botania thinks it's a food source for the Munchdew?

**Comment by P3pp3rF1y** [comment]
When you say that it does show in log when it doesn't crash. Could you show the log? Is it really the bucket issue and not the journeymap one?

**Comment by piedpipr314** [comment]
the line: "at net.minecraft.client.renderer.block.model.ModelBakery.func_177586_a(ModelBakery.java:185)" is the one that I found similar.  Also, my pack works perfectly without Botania, and it worked well before without EnderIO and WITH Botania, further testing I go.

**Comment by P3pp3rF1y** [comment]
just put the log on pastebin/hastebin or such and link it here so that we get the full view of the stacktrace to compare. it may be the same issue, but it may also be yet another thing happening here

**Comment by piedpipr314** [comment]
Is there a specific line I should look for?  It's a huge pack with many mods and rather difficult for someone else to parse through.  I'm trying to help you help us.

**Comment by P3pp3rF1y** [comment]
well, it's alright to put the full log on hastebin, it's fairly easy to search through it. But at least I would like to see the full stacktrace of the exception - what's logged after [Client thread/ERROR] before the next [Client thread/INFO or WARN]

**Comment by piedpipr314** [comment]
Yeah, I think these warnings are from JourneyMap, I'm seeing a lot of that in here.

**Comment by piedpipr314** [comment]
https://pastebin.com/Ex3G2DHG  This is without Journeymap AND Botania

**Comment by piedpipr314** [comment]
doesn't actually show "ERROR" or "WARN"

**Comment by P3pp3rF1y** [comment]
But that's JsonSyntaxException coming from CCL that's completely unrelated to this issue. I thought you were getting something at least with ModelBakery?

**Comment by piedpipr314** [comment]
Gotcha.  I can tell you guys that Botania for some reason does not like MFR.  I thought it was EnderIO as well, but I disproved it myself.

**Comment by piedpipr314** [comment]
I think that Botania considers the Vanilla Milk bucket as a food for the Munchdew (I wouldn't know).  It doesn't understand the MFR Milk bucket perhaps?

**Comment by piedpipr314** [comment]
I feel like I'm going in circles, and giving you guys a wild goose chase.  I really WANT a smaller pack to crash and figure this out, and it DOESN'T!

**Comment by P3pp3rF1y** [comment]
I have just ran an instance with botania included and I am not getting any issue at all even with muchdew in world and milk bucket next to it. 

So instead of speculating, let's actually look into some concrete stuff related to this issue. If you're actually getting any exceptions with botania just include it here, but otherwise it's just speculation. 
And yes we know that it crashed in bigger packs and it may well be that the issue is in forge and only manifests in larger packs.
And really if you want to get rid of it just disable the bucket. we will likely look into a forge change so that we don't have to override bucket at all.

**Comment by piedpipr314** [comment]
Well, I'd like to help you guys figure this out (if it is indeed MFR's fault).  I don't give up easily.

**Comment by piedpipr314** [comment]
Yes, with Botania and the MFR Milk bucket enabled, it causes the crash at the top.  Without Botania, the session loads.
My log: https://pastebin.com/JWcQEqjx

**Comment by P3pp3rF1y** [comment]
so I just tried with dw20 pack (which is the only one I could get to crash with this so far) and it's true that removing botania helped, but it still crashed on the third time I tried to start the pack with the same stack so it's not botania or just botania.

**Comment by piedpipr314** [comment]
@P3pp3rF1y Well, should you think of anything that I can try, I'm willing to adjust packs and work with you guys on this.  If it bothers me for your sake, it probably bothers you more.  I honestly don't care if I need to disable the bucket, I'm just trying to help.

**Comment by piedpipr314** [comment]
This may be unrelated, I honestly don't know.  However, Tinkers' Construct adds "tconstruct:milk" that acts very much like your "minefactoryreloaded:milk_fluid".  If you happen to have an instance that doesn't crash with those two mods, you can just give yourself the sources with a /give command and check yourself.  I do not know how this is normally crafted, as the instance I'm using that does not crash shows no recipe for it.  They could very well be trying to overwrite one another though.

**Comment by FlaggedBrad** [comment]
Disable the milk bucket override in your minefactory reloaded config file, it worked for me
