### ISSUE TITLE
MineFactoryReloaded-[1.10.2]2.9.0B1-226 causing startup crash.

### ISSUE THREAD

**Issue by border999** [skyboy/MineFactoryReloaded#648]
It should be noted that optifine is involved most likely: OptiFine_1.10.2_HD_U_E3
https://pastebin.com/Ap9E2KaF
It's some form of rendering error with the milk bucket.

**Comment by skyboy** [comment]
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/646

**Comment by FlaggedBrad** [comment]
Disable milk bottles in your minefactory reloaded config file, it worked for me
