### ISSUE TITLE
[Question] 1.11.2/1.12?

### ISSUE THREAD

**Issue by 016Nojr** [skyboy/MineFactoryReloaded#649]
What are the current plans for MFR? 

Stay on 1.10.2, go to 1.11.2 then 1.12, or straight to 1.12 from 1.10.2?

**Comment by TheSnowyChickens** [comment]
It would be nice for 1.12 , and since 1.12 has such a good performance it would be nice to have this mod updated.

**Comment by Fundryi** [comment]
yup 1.12 would be the best! :) I don't see why you would still want to work on 1.10 & 1.11 at this point anyway.

**Comment by mminkus** [comment]
It seems like MFR might be abandoned :(

**Comment by ben-mkiv** [comment]
Because many mods aren't ported to 1.12 yet, and porting to 1.10.2 involves almost the same changes as porting to 1.12 so its easier to port to 1.12 from a working 1.10.2 release instead of going straight for 1.12 from 1.7.10
