### ISSUE TITLE
Can't grab fisher from crafting table.

### ISSUE THREAD

**Issue by Slendigo** [skyboy/MineFactoryReloaded#650]
It just stays in the crafting table.

**Comment by P3pp3rF1y** [comment]
we will need more details than this
- version of MFR
- what recipe are you using - vanilla/enderio?
- is it in a pack? Does it happen if you try it with just MFR?

I have just tried in a small pack with MFR and I can easily craft it. Also it uses regular basic recipe implementation so it's very likely that you have it in a pack where another mod interacts with this recipe in not nice way.

**Comment by skyboy** [comment]
Server and client probably have mismatched recipe configs.
