### ISSUE TITLE
[1.10.2] crash on startup

### ISSUE THREAD

**Issue by Jamez1123** [skyboy/MineFactoryReloaded#652]
[crash-2017-07-13_01.02.17-client.txt](https://github.com/skyboy/MineFactoryReloaded/files/1144447/crash-2017-07-13_01.02.17-client.txt)
 when i remove mfr the pack works just fine

**Comment by P3pp3rF1y** [comment]
You're using dev - deobfuscated - build that is of course not going to run in obfuscated environment. Just download non dev file on curseforge - the file that you get if you just click on download button.

**Comment by Jamez1123** [comment]
Thank you ill try that when I get home

**Comment by Jamez1123** [comment]
Okay so i tried a few things first i tried as you suggested by just simply hitting the download button but, it gave me the 1.7.10 version not the 1.10.2 version i want. Then i tried the latest beta version.. just to get the same error but in conflict with a different mod this time.
[crash-2017-07-13_13.36.13-client.txt](https://github.com/skyboy/MineFactoryReloaded/files/1146621/crash-2017-07-13_13.36.13-client.txt)
Is there just not a stable version for 1.10.2?

**Comment by piedpipr314** [comment]
https://mods.curse.com/mc-mods/minecraft/minefactory-reloaded/2444177  This becomes much easier through the Twitch/Curse launcher.  It's how I get all my mods nowadays.

**Comment by Jamez1123** [comment]
Well that didn't work. It is giving the same error.

**Comment by piedpipr314** [comment]
See https://github.com/skyboy/MineFactoryReloaded/issues/646

**Comment by Jamez1123** [comment]
soooooo.... i just loaded the pack a few times and ran into no errors.. i have no idea what happened but it all works now
