### ISSUE TITLE
A couple of issues I've noticed

### ISSUE THREAD

**Issue by GamerbyDesign** [skyboy/MineFactoryReloaded#659]
All the machines have the wrong name in WAILA.

The Harvester will keep harvesting after its full of sludge.

The Grinder does not output to item ducts.

Using MineFactoryReloaded-[1.10.2]2.9.0B1-229

**Comment by GamerbyDesign** [comment]
BTW Thank you for porting this from 1.7.10.  That was the only version I was playing before this got ported.

**Comment by GamerbyDesign** [comment]
The steam turbines don't seem to be glitchy as they don't output they're power sometimes unless removing  steam input from them.

**Comment by GamerbyDesign** [comment]
Grinders do no pick up Blaze rod as drops.

**Comment by GamerbyDesign** [comment]
Recipe for Hardened Fluiduct is not showing up in JEI/NEI

**Comment by TH3GOD88** [comment]
Hardened Fluiduct is Thermal Dynamics.

**Comment by GamerbyDesign** [comment]
You are correct sir however I thought all those mods

**Comment by TH3GOD88** [comment]
Yes; he does help on them; but they should be reported to the CoFH Team. There should be a place to send a report to.

**Comment by SwallowSearching** [comment]
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

UCHI MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UCHI MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UD MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UD MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UCHI MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UD MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UD MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UD MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UCHI MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UD MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UCHI MineFactoryReloaded|CompatMagicalCrops{1.2.4} [MFR Compat: MagicalCrops] (MFR Compat - Magical Crops v1-2-4.jar) 
> UD MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UD MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UD MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UCHI MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UCHI MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UCHI MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
> UCHI MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
