### ISSUE TITLE
1.10.2 broken mcmod.info? / Uncraftable items?

### ISSUE THREAD

**Issue by Omegapex** [skyboy/MineFactoryReloaded#668]
The in-game forge mod options list appears to not recognise the info file? which is strange because it is clearly there.

Also, I've been unable to craft any of the minefactory reloaded items whatsoever, checked the configs and all recipes are enabled and set to thermal expansion recipes. The items exist in-game but trying to check recipes with jei doesn't display any recipes, and trying to uncraft one that I spawned in corrupted my world...

I think these may be linked? i'm not very savvy with this kind of stuff. 
I have tried redownloading and using latest and a few older versions, as well as deleting the config files to let new ones generate. All with no results

I love this mod and hope that the issue can be dealt with so I can use it again :)

**Comment by Omegapex** [comment]
Update: I tried enabling all three crafting recipe sets (EnderIO, TE, and vanilla) it seems that no thermal expansion recipes are showing up, and several enderio ones aren't either... vanilla recipes are fine though.

**Comment by GamerbyDesign** [comment]
What aren't you able to craft?

**Comment by ShmooSmith** [comment]
How do you make it so the crafting recipes are all the vanilla versions? Some of my MFR blocks are uncraftable for some reason.
