### ISSUE TITLE
[1.10.2] Lavafabricator stores to much

### ISSUE THREAD

**Issue by Sanofus** [skyboy/MineFactoryReloaded#669]
The lavafabricator stores more than than it could. 
![2017-08-21_08 56 41](https://user-images.githubusercontent.com/26455012/29507166-3981c91c-864f-11e7-859f-fdfbe36dd832.png)

**Comment by P3pp3rF1y** [comment]
I am unable to recreate this one and looking through the code the only way I see this could happen is if some pipes tried to take negative amounts of lava from the fabricator. 
Would you be able to provide more info on how you got this?

**Comment by JonasCiss** [comment]
I can tell you that I used Hardened Fluidducts of Thermal Dyamics that were connected to Smeltery Tanks of Tinkers Construct.
