### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by simox66** [skyboy/MineFactoryReloaded#670]
Hello, in my server, I found out a bug: when I place the grinder, the server crashes. I also tried to follow the tips you gave other users before (upgrade Forge, CoFH Core, Sponge), but it doesn't work either.
Crash Report of the Official Server: https://hastebin.com/oyoqejunih.rb
 Crash Report of the Test Server: https://hastebin.com/geqagekesa.scala

**Comment by bloodmc** [comment]
This has been addressed in SpongeForge and can be closed.
