### ISSUE TITLE
[1.10.2] Sewer wont refill

### ISSUE THREAD

**Issue by stanedav** [skyboy/MineFactoryReloaded#673]
Hello I have problem with Sewer - when I empty this machine its never get refilled by sewage - it remains empty. 

MC: 1.10.2
MFR:  MineFactoryReloaded-[1.10.2]2.9.0B1-226.jar
Core: CoFHCore-1.10.2-4.1.12.17-universal.jar

**Comment by P3pp3rF1y** [comment]
Any additional info you can provide on this? (using pipes / buckets / anything else to take sewage out)
I don't seem to be able to recreate.
