### ISSUE TITLE
Block Smasher Game Crash

### ISSUE THREAD

**Issue by triffman33** [skyboy/MineFactoryReloaded#674]
Every time I place a block smasher, I get this crash:

https://pastebin.com/ma6Yd9hz 

I am running foolcraft version 2.0 which runs the latest version of minefactory reloaded.

To reproduce, just place the block smasher down (only been able to test in singleplayer) and your game will crash.

**Comment by iDarper** [comment]
This is also happening on our custom 1.10.2 pack. This apparently not as isolated as we thought.

**Comment by Siriuo** [comment]
I am also experiencing this issue.

**Comment by DV666** [comment]
Same for me :/
