### ISSUE TITLE
[1.10.2] Game crashes at forge startup

### ISSUE THREAD

**Issue by pcking99** [skyboy/MineFactoryReloaded#675]
Game crashes at forge loading. in step 3/7 Modelling.
I have added mods and tested by removing COFH core, Thermal Expansion, Foundation and MineFactory. After adding the mods back one by one i found out MineFactory creates a problem. Can it be fixed cause its a really good mod.

The mod i added: https://minecraft.curseforge.com/projects/practical-logistics-2
If you need anything more then ask me and ill see what i can do.

MC: 1.10.2
COFH Core: 4.1.12.17 universal
MineFactory: 2.9.0B1-229
Log: https://www.dropbox.com/s/1rre45x20hr8vo0/crash-2017-09-12_15.59.43-client.txt?dl=0

**Comment by iDarper** [comment]
I just browsed your logs, and It doesn't say anywhere that MFR is the culprit. It's not even erroring. Have you double checked the ammount of RAM you are sending to the client?

**Comment by pcking99** [comment]
I have assigned 15GB ram to my computer for this custom modspack.
After removing MFR my game start with no problem and i could add new mods wich i couldnt before.

**Comment by pcking99** [comment]
Here is the newes logs from the crashing after i try MFR again.
https://www.dropbox.com/sh/yzcinnz4j7fvuzq/AADEazNPh56PcJcFWBwu_PDfa?dl=0

**Comment by pcking99** [comment]
I see something about CoFH core and Tesla. CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * An unsupportted RF API is installed (1.7.0 from (guessing) jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/CoFHAPIProps.class).
                    Ender IO needs at least 1.4.0 and will NOT work with older versions.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/Tesla.class
                  * Tesla API class 'TeslaCapabilities' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/capability/TeslaCapabilities.class
                  * Tesla API class 'ITeslaConsumer' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/ITeslaConsumer.class
                  * Tesla API class 'ITeslaHolder' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/ITeslaHolder.class
                  * Tesla API class 'ITeslaProducer' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/ITeslaProducer.class
                  * Tesla API class 'BaseTeslaContainer' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/implementation/BaseTeslaContainer.class
                  * Tesla API class 'BaseTeslaContainerProvider' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/implementation/BaseTeslaContainerProvider.class
                  * Tesla API class 'InfiniteTeslaConsumer' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/implementation/InfiniteTeslaConsumer.class
                  * Tesla API class 'InfiniteTeslaConsumerProvider' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/implementation/InfiniteTeslaConsumerProvider.class
                  * Tesla API class 'InfiniteTeslaProducer' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/implementation/InfiniteTeslaProducer.class
                  * Tesla API class 'InfiniteTeslaProducerProvider' is loaded from: jar:file:/C:/Users/kimro/AppData/Roaming/.technic/modpacks/test-automat-pack/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/implementation/InfiniteTeslaProducerProvider.class

**Comment by pcking99** [comment]
downgraded to first release of MFR and ender zoo, now it starts without a problem.
