### ISSUE TITLE
[1.10.2] Game begins to start, then crashes.

### ISSUE THREAD

**Issue by PyrrhicVictory7** [skyboy/MineFactoryReloaded#677]
Here is the log. FYI this is the only mod that is causing the problem, I run Forge fine without it.

[net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-1.10.2-0007-full.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  IC2core (industrialcraft-2-2.6.252-ex110.jar)
  AppleCore (AppleCore-mc1.10.2-2.2.2.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 9/15/17 7:06 PM
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at com.google.common.base.CharMatcher$NegatedMatcher.<init>(CharMatcher.java:635)
	at com.google.common.base.CharMatcher.negate(CharMatcher.java:623)
	at com.google.common.base.CharMatcher.retainFrom(CharMatcher.java:1095)
	at net.minecraftforge.fml.client.FMLClientHandler.stripSpecialChars(FMLClientHandler.java:1035)
	at net.minecraftforge.fml.common.FMLCommonHandler.stripSpecialChars(FMLCommonHandler.java:743)
	at net.minecraftforge.fml.common.ProgressManager$ProgressBar.step(ProgressManager.java:126)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:175)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at com.google.common.base.CharMatcher$NegatedMatcher.<init>(CharMatcher.java:635)
	at com.google.common.base.CharMatcher.negate(CharMatcher.java:623)
	at com.google.common.base.CharMatcher.retainFrom(CharMatcher.java:1095)
	at net.minecraftforge.fml.client.FMLClientHandler.stripSpecialChars(FMLClientHandler.java:1035)
	at net.minecraftforge.fml.common.FMLCommonHandler.stripSpecialChars(FMLCommonHandler.java:743)
	at net.minecraftforge.fml.common.ProgressManager$ProgressBar.step(ProgressManager.java:126)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:175)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 189724288 bytes (180 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	io.github.elytra.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	infinitylib{1.10.2-0.11.0} [InfinityLib] (infinitylib-0.11.0.jar) 
	UCHIJA	agricraft{2.0.0-0.10.0-a19} [AgriCraft] (agricraft-2.0.0-0.10.0-a19.jar) 
	UCHIJA	AppleCore{2.2.2} [AppleCore] (AppleCore-mc1.10.2-2.2.2.jar) 
	UCHIJA	bdlib{1.12.4.24} [BD Lib] (bdlib-1.12.4.24-mc1.10.2.jar) 
	UCHIJA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2236} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2236-universal.jar) 
	UCHIJA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UCHIJA	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJA	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UCHIJA	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UCHIJA	movingworld{1.10.2-0007} [Moving World] (movingworld-1.10.2-0007-full.jar) 
	UCHIJA	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.10.2-0006-full.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHIJA	EnderIO{1.10.2-3.1.183} [Ender IO] (EnderIO-1.10.2-3.1.183.jar) 
	UCHIJA	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCHIJA	exnihiloadscensio{0.1.5} [Ex Nihilo Adscensio] (exnihiloadscensio-1.10.2-0.1.20.jar) 
	UCHIJA	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UCHIJA	IC2{2.6.252-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.252-ex110.jar) 
	UCHIJA	substratum{1.8.2.1} [Substratum] (Substratum-1.10.2-1.8.2.1.jar) 
	UCHIJA	exnihiloomnia{1.2.6} [Ex Nihilo Omnia] (exnihiloomnia-1.2.6.jar) 
	UCHIJA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.6.1.jar) 
	UCHIJA	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCHIJA	foundry{2.2.3.0} [Foundry] (Foundry-1.10.2-2.2.3.0.jar) 
	UCHIJA	ironbackpacks{1.10.2-2.2.31} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.31.jar) 
	UCHIJA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJA	minefactoryreloaded{2.9.0B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.10.2]2.9.0B1-221.jar) 
	UCHIJA	MineFactoryReloaded|CompatVanilla{2.9.0B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.10.2]2.9.0B1-221.jar) 
	UCHIJA	moreoverlays{1.11} [MoreOverlays] (moreoverlays-1.11-mc1.10.2.jar) 
	Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-1.10.2-0007-full.jar)
  
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
IC2core (industrialcraft-2-2.6.252-ex110.jar)
  
AppleCore (AppleCore-mc1.10.2-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4574' Renderer: 'Intel(R) HD Graphics 520'
	minefactoryreloaded: -[1.10.2]2.9.0B1-221
	List of loaded APIs: 
		* AgriCraftAPI (1.0) from agricraft-2.0.0-0.10.0-a19.jar
		* AppleCoreAPI (2.3.0) from AppleCore-mc1.10.2-2.2.2.jar
		* CoFHAPI (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.4.3.jar
		* cofhapi (1.7.0) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhapi|block (1.7.0) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhapi|core (1.7.0) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.4.3.jar
		* cofhapi|energy (1.7.0) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhapi|item (1.7.0) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.4.3.jar
		* cofhapi|tileentity (1.7.0) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhapi|util (1.7.0) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|audio (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|gui (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|gui|container (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|gui|element (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|gui|element|listbox (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|gui|slot (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|inventory (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|util (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|util|helpers (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|world (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|world|feature (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* compatlayer (0.2.9) from compatlayer-1.10-0.2.9.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.1.183.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.1.183.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.1.183.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.1.183.jar
		* foundry.api (2.2.0.0) from Foundry-1.10.2-2.2.3.0.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-61.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-61.jar
		* IronBackpacks|API (0.5) from IronBackpacks-1.10.2-2.2.31.jar
		* mcjtylib_ng (2.4.3) from mcjtylib-1.1x-2.4.3.jar
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	ChickenChunks Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * An unsupportted RF API is installed (1.7.0 from (guessing) jar:file:/C:/Users/jackv/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/CoFHAPIProps.class).
                    Ender IO needs at least 1.4.0 and will NOT work with older versions.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/jackv/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/jackv/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/jackv/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/jackv/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/jackv/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/jackv/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/jackv/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/jackv/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/jackv/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

**Comment by iDarper** [comment]
You don't have enough ram allocated to the client

**Comment by PyrrhicVictory7** [comment]
Ill give that a go, thx!

**Comment by MineBartekSA** [comment]
There is a OutOfMemoryError on the beggining of the issue and crash report. So like iDarper sayed you don't have enough memory. (MC don't have enough RAM if you don't understend xD)

For the next time first try to look up for the MAIN error that is on the beggining of the crash report.
