### ISSUE TITLE
Fruit Picker in Infinite Idle

### ISSUE THREAD

**Issue by DigitalSketch** [skyboy/MineFactoryReloaded#679]
This is my first time using MineFactory, so I may be doing something wrong, but the fruit picker I put down is constantly in an "Idle" loop, and never goes into "working".

I've put a diamond chest at the back of it to collect drops, and I've put power to the bottom, top and sides of the block.  I have the block facing the Pam's harvestcraft trees.  I've put the picker at the bottom of the tree, and at the level of the fruits.

The JAR file  in the pack is [1.10.2]2.9.0B1-229

**Comment by RyanP1991** [comment]
I know previously that the picker should work with Pam's stuff, I checked quickly and the block still harvests cocoa beans perfectly fine.
