### ISSUE TITLE
minefactory planter crashing with biomes o plenty dirt

### ISSUE THREAD

**Issue by scalda** [skyboy/MineFactoryReloaded#680]
please see [crash log](https://pastebin.com/B817ttKF)

https://github.com/scalda/FoolCraft/issues/736

using MFR version 1.10.2 229

**Comment by P3pp3rF1y** [comment]
Just putting a note for myself here, hopefully I will have a chance to fix this:

Incorrect position and state passed to canSustainPlant in PlantableStandard

groundId.canSustainPlant(world.getBlockState(pos), world, pos, EnumFacing.UP, (IPlantable)_block)
needs to be changed to 
groundId.canSustainPlant(world.getBlockState(pos.down()), world, pos.down(), EnumFacing.UP, (IPlantable)_block)

**Comment by scalda** [comment]
thank you for the quick response

**Comment by P3pp3rF1y** [comment]
Well, that was just me taking a note, really. I would like to fix this, but with skyboy MIA I don't have a way to get the fix out at the moment. Hopefully he comes back soon.

**Comment by scalda** [comment]
hey making a note is better then nothing lol
