### ISSUE TITLE
[1.10.2] Can't craft a Pink Slime Block

### ISSUE THREAD

**Issue by Krabjuk** [skyboy/MineFactoryReloaded#683]
I'm using MineFactoryReloaded-[1.10.2]2.9.0B1-229 for Minecraft 1.10.2 with Forge 12.18.3.2511.

Currently it seems not possible to craft a pink slime block out of 9 pink slime balls. The recipe gives just a regular slime block. That makes it impossible for me to craft the pink slime crystal.

I've tried this mod version running without any other mods, except the required ones (
CoFHCore-1.10.2-4.1.12.17-universal and CodeChicken Lib 1.10.2-2.5.9.283-universal) but the problem remains.

Am I doing something wrong or is this a bug?

**Comment by HD97300** [comment]
@Krabjuk to craft `Pink Slime Block` you can use `Worktable` from Forestry

**Comment by Krabjuk** [comment]
Seems there is no other solution than the forestry worktable.

Thanks.
