### ISSUE TITLE
Update For 1.12.2

### ISSUE THREAD

**Issue by kenijey** [skyboy/MineFactoryReloaded#688]
sorry for disturbing. will this mod be updated to newer versions of minecraft such as 1.12? can you please? thanks.

**Comment by JonasCiss** [comment]
You can use Industrial Foregoing as a good alternative mod.

**Comment by kenijey** [comment]
but it doesn't have advanced miner :D

**Comment by JonasCiss** [comment]
Indee Mine Factory Reloaded does not have a advanced miner because that is a block added by Industrial Craft 2.

**Comment by kenijey** [comment]
oh... why don't industrial foregoing developer add that machine? i love it...

**Comment by JonasCiss** [comment]
Why don't you add Industrial Craft 2 instead? It is already updated to 1.12.2..

**Comment by kenijey** [comment]
whaat, i wasn't aware of it does add that block to industrial foregoing... i was using tech reborn. lol. now i'm confused about should i delete tech reborn then add industrial craft...

**Comment by JonasCiss** [comment]
Why don't you keep both? They should work together,
However the advanced miner seems to be a quarry. The Digital Miner of Mekanism has the same funtionality. You can add this instead if you don't want mods that are too similar.

**Comment by kenijey** [comment]
yeah i dont want mods together that too similar. i will look at digital miner from mekanism.
i think i will replace techreborn with industrialcraft, or add mekanism may be..
