### ISSUE TITLE
1.10.2 Block Smasher Crash

### ISSUE THREAD

**Issue by janjao12** [skyboy/MineFactoryReloaded#698]
Hey, I'm having an issue when I place the "block smasher"
when I place this block my game crashes instantly
here is the Crash report: https://pastebin.com/z56h0XRT
so, when I reopen my game and try to enter the map
I got a server crash, here is: https://pastebin.com/aPt8ePw5

my only way to "uncrash" was deleting the block with MCEDIT
but I want to USE this block, there's no fix?
MFR Latest version (MineFactoryReloaded-[1.10.2]2.9.0B1-230)
COFH latest too (CoFHCore-1.10.2-4.1.12.17-universal)
Forge 12.18.3.2239

**Comment by Kurbackiy** [comment]
Same problem. 
[crash-2018-03-23_16.35.47-client.txt](https://github.com/skyboy/MineFactoryReloaded/files/1841537/crash-2018-03-23_16.35.47-client.txt)

**Comment by piousminion** [comment]
Same deal. :(
https://paste.ee/p/MZeyT

**Comment by piousminion** [comment]
@P3pp3rF1y
I guess this fix wasn't as effective as previously thought?
#684 c33a33c97132ba51b0021688450809b82978c15b

**Comment by janjao12** [comment]
I've just removed the block smasher with MCEDIT and used another options for the same work as the block smasher does.
I don't play in the map for a while, but I remember what I did. I used the block constructor and block destructor from Refined Storaged (destructor with Fortune upgrade) and it worked well.

**Comment by piousminion** [comment]
Well that's kind of messed up.  I use a slightly older version of minecraft because a lot of mods don't support the latest right away, only to find out the the mods that do, don't support the older. *sigh*

**Comment by skyboy** [comment]
MFR has never properly supported 1.10.2, and was never released for it. Just alphas and betas provided.

**Comment by piousminion** [comment]
Code was written for it. Was there some notice that beta would not be supported or that 1.10.2 wouldn't be?  Surely you can understand our viewpoint. It is what it is though. *sigh*

**Comment by skyboy** [comment]
Code is written for things that end up unsupported or removed all the time, it's the nature of software. And while there was no notice it would end up unsupported, there was no notice that I would be unable to write code for it for a year either. Shit happens, 1.12 is coming along though.
