### ISSUE TITLE
Harvester is not only for 11x11

### ISSUE THREAD

**Issue by DarkMono** [skyboy/MineFactoryReloaded#699]
I put a harvester with 9x9 modify and he start to dig all the trees in the area of 100 blocks and more
![2018-05-13_19 58 54](https://user-images.githubusercontent.com/39243521/39969733-31def0de-56e9-11e8-9020-ff4bcb5d0ffa.png)
![2018-05-13_19 58 33](https://user-images.githubusercontent.com/39243521/39969734-344c0488-56e9-11e8-8b80-1b3a37e81b1f.png)
![2018-05-13_19 59 09](https://user-images.githubusercontent.com/39243521/39969737-35b750ac-56e9-11e8-9a40-a0d32a4e735c.png)
![2018-05-13_19 58 51](https://user-images.githubusercontent.com/39243521/39969739-3781cbba-56e9-11e8-8100-0a3e42715a09.png)

**Comment by skyboy** [comment]
The harvester is unable to distinguish where one tree ends and another begins - if one in your farm touches one outside your farm, the harvester will keep going until there are no more connected blocks.
