### ISSUE TITLE
[1.12.2][2.9.0B1.1-universal] Crash with CoFHWorld

### ISSUE THREAD

**Issue by Diamondman121314** [skyboy/MineFactoryReloaded#703]
I'm not completely sure if I'm right here, but it looks like it's crashing with CoFHWorld when trying to generate something. Felt as I should report this just in case it's not known about.

https://pastebin.com/7F4EV5WB

**Comment by Sanofus** [comment]
Where did you get the 1.12.2 beta from?

**Comment by Diamondman121314** [comment]
@Sanofus I compiled it myself just so I could try it, I've been waiting so long for it. I'll have to do it again as this was fixed. >_>
