### ISSUE TITLE
[1.12.2][2.9.0B1.1-universal] Crash with what looks like IC2 recipes

### ISSUE THREAD

**Issue by Diamondman121314** [skyboy/MineFactoryReloaded#704]
Another crash seems to be with IC2 recipes, even though I don't have IC2 included. The jar was compiled from commit `0d2bbf2`, as the last one won't compile.

https://pastebin.com/QsrDj5Dc

**Comment by skyboy** [comment]
Fixed by https://github.com/skyboy/MineFactoryReloaded/commit/0d2bbf26f7f67e2539fb920f715ccd27db815389

**Comment by Diamondman121314** [comment]
Oops, I didn't even notice I put the wrong commit down from the one I compiled, but thanks anyway! :)
