### ISSUE TITLE
Unifer Problem

### ISSUE THREAD

**Issue by NicolaosGreene** [skyboy/MineFactoryReloaded#77]
Something in it is causing the Unifier from Minefactory Reloaded (MFR) not be able to convert Aluminum Ingots while the DragonAPI is present. I tested this by having Emasher's resource 1.2.1.8, Minefactory Reloaded 2.7.4, PowerCrystalsCore 1.1.8-9, Tinker's Construct 1.5.2.4, DragonAPI 1.6 v13. When I had all those mods installed I am unable to use the Unifier from MFR to convert the aluminium ingots from Emasher's resource to the aluminum ingots from Tinker's Construct. However, if you remove DragonAPI this works properly.
Let me know if you need any more information and thanks for your time.
-Nicolaos

**Comment by ipatrol** [comment]
This would be understandable, except some mods have a habit of adding entries like "oreAnyCopper" and "ingotAnyBronze". I'm not sure which mod came up with this bright idea, but it has the effect of frustrating attempts at unifying a number of items. I would suggest that these "*Any*" entries be configured to be ignored by the Unifier. This could be implemented using a list in the config file for added flexibility.
